### ISSUE TITLE
improve serve compile time

### ISSUE THREAD

**Issue by mxrlkn** [netlify/netlify-lambda#103]
I use a npm module that takes quite a bit of time to import when running `netlify-lambda serve`.

The problem is that it takes the same amount of time each time I save which makes the development process very slow.

It looks like netlify-lambda is building all the files from scratch, instead of only building the parts that have changed.

I've switched to https://github.com/iiroj/lambda-dev which works just like that. But it would be nice to have it in the official library.

An alternative could be an option that disables the build part and just serves the files directly. Of course you'd have to keep your code compatible with whatever node version it's running on.

**Comment by sw-yx** [comment]
PR is welcome for incremental builds :)

for the alternative without building, it exists: https://github.com/netlify/netlify-lambda#--static-option

**Comment by sw-yx** [comment]
closing: netlify-lambda will only accept bugfixes for now. we will have other updates in store.
