### ISSUE TITLE
Where does v1.2.0 come from?

### ISSUE THREAD

**Issue by riddla** [netlify/netlify-lambda#104]
Hi there.

https://www.npmjs.com/package/netlify-lambda/v/1.2.0 tells me, that a newer version than provided by this repository exists. Where does it come from?
I wanted to submit some pull requests but stumbled upon some differences. My project in case did have the `1.2.0` e.g. `latest` version and now I don't know which version I should put my additions in ...

**Comment by sw-yx** [comment]
hi! just use the current master. there arent any substantive changes since 9 days ago. i think i may have screwed up the release tagging, so if you were relying on that, apologies for the screwup.

fyi, n-l will only accept bugfixes for now. we have other updates in store.

**Comment by riddla** [comment]
Understood. Which updates are you planning? Is there a roadmap somewhere?

I got two things locally, which I could provide:

- A fix for https://github.com/netlify/netlify-lambda/issues/99 (if you consider this a bug?).
- A simple express root page thats lists and links the exiting functions when served locally.

**Comment by sw-yx** [comment]
not yet announced but stay tuned on the netlify blog/twitter/etc. i will also update this repo when appropriate.

happy to take a PR for #99! i dont test enough i guess 😅 

lets work on the other and any other ideas you have at a later date
