### ISSUE TITLE
Clarify --config option

### ISSUE THREAD

**Issue by bcomnes** [netlify/netlify-lambda#110]
What does this flag take? settings? json? a path? We should clarify this in the README.

**Comment by bcomnes** [comment]
What this means is:

Have a file with:


```js
# webpack.functions.js 
module.exports = {
  optimization: { minimize: false }
};
```

Then specify `--config ./webpack.functions.js`.  Found here: https://github.com/netlify/netlify-lambda/issues/64#issuecomment-429625191

**Comment by sw-yx** [comment]
addressed
