### ISSUE TITLE
Using local environment variables

### ISSUE THREAD

**Issue by azdanov** [netlify/netlify-lambda#118]
Is there a way to specify environment variables for `netlify.toml` for local development?

As I understand this file is required during build stage on netlify and needs to be included inside the GitHub repository, for example. But this way it's impossible to hide any environment variables, such as API keys.

Are there any ways similar to `create-react-app` where `.env.local` is used, but ignored via `.gitignore`.

After messing around I found a workaround by specifying a `webpack.functions.js` that picks up `.env`:

```js
const Dotenv = require('dotenv-webpack')

// @see https://github.com/netlify/netlify-lambda#webpack-configuration
module.exports = {
  plugins: [new Dotenv()],
}
```

If this is the best way, then it could be useful mentioning this approach in the readme.

**Comment by sw-yx** [comment]
indeed i think this is the best way right now. we are working on some features to help with the API security but it wont address your usecase i think. good job on figuring out the workaround. we will definitely need better support for this.

**Comment by lemonboston** [comment]
I tried this and see that dotenv picks up the .env file (because I see error message when it doesn't), but process.env still doesn't contain the variable when accessed in a function. Any tips where to look?

**Comment by b-reklass** [comment]
@sw-yx This is fixed on production, but appears to have the same bug when storing @ localhost. Would be nice to have it persist on both for testing purposes.

**Comment by iamskok** [comment]
Are there any updates? I also find a hard time making my functions use the same NODE_ENV as  the rest of my Gatsby project. I would prefer not to change the variable thru netlify Admin each time I do development. 

Here is the question about it on [netlify forum](https://community.netlify.com/t/how-to-change-node-env-for-netlify-functions/1366)

**Comment by ceddlyburge** [comment]
> After messing around I found a workaround by specifying a `webpack.functions.js` that picks up `.env`:

Hi @azdanov, this doesn't work for me, please can you let me know where is your .env file located?

Thanks

Cedd

**Comment by taktran** [comment]
@ceddlyburge, it took a while for me to figure out how to set it up correctly too, so I'll post how I got it working here for prosperity.

You need to:

* `npm install dotenv-webpack` on the root folder where you run `netlify-lambda`
* Create the `.env` file in the root
* As per https://github.com/netlify/netlify-lambda#webpack-configuration
  * Create a `webpack.functions.js` file with the above contents

        const Dotenv = require('dotenv-webpack')

        // @see https://github.com/netlify/netlify-lambda#webpack-configuration
        module.exports = {
          plugins: [new Dotenv()],
        }

  * To run it all: `netlify-lambda serve --config ./webpack.functions.js` in the root folder

---

Also a gotcha I found with `dotenv-webpack` was that you can't destructure `process.env` variables because of how it replaces them in webpack ie,

Don`t do

```
const { API_KEY }  = process.env.API_KEY;
```

Instead, do

```
const API_KEY = process.env.API_KEY;
```

**Comment by ceddlyburge** [comment]
Thanks very much Tak, I owe you a favour :)

**Comment by anwittw** [comment]
Hi all, 

thanks for the explanation above. I tried to apply this to my react project, but get an error when executing the script: 

```
> netlify-lambda serve --config ./webpack.functions.js

error: missing required argument `dir'
npm ERR! code ELIFECYCLE
```

Any ideas, would be appreciated! 

thanks

**Comment by itzmanish** [comment]
Doesn't work with gatsby 3
