### ISSUE TITLE
NODE_ENV is always `production`

### ISSUE THREAD

**Issue by Neddz** [netlify/netlify-lambda#119]
Hello! I am having some trouble with the following:

I have been trying to overwrite the NODE_ENV variable with no success.

If I do:
`NODE_ENV=development netlify-lambda build <folder>`
all the functions inside `<folder>` will have the `process.env.NODE_ENV` set to `production`. I believe this might be because webpack is always run in production mode.

Please let me know if I am doing anything wrong.

Thank you!

**Comment by sw-yx** [comment]
hi,

yes, the line is here https://github.com/netlify/netlify-lambda/blob/d0cb7444a538eedd1a530d3eac093cdbf4a32c97/lib/build.js#L72

pr welcome if you wanna fix

**Comment by azdanov** [comment]
As a workaround you could define a `webpack.functions.js` with:

```js
const webpack = require('webpack')

module.exports = {
  plugins: [
    new webpack.EnvironmentPlugin({ NODE_ENV: 'development' }),
  ],
}
```

And run `netlify-lambda --config webpack.functions.js build src/lambda`. This way it's possible to load any env variables from CI or Netlify.

**Comment by sw-yx** [comment]
released with https://github.com/netlify/netlify-lambda/releases/tag/v1.4.3
