### ISSUE TITLE
Error [ERR_STREAM_WRITE_AFTER_END]: write after end

### ISSUE THREAD

**Issue by designbuedchen** [netlify/netlify-lambda#120]
Hi guys!

After entering

> yarn netlify-lambda serve src/lambda

in the console and hitting e.g. http://localhost:9000/.netlify/functions/hello everything runs well and the console returns

> Request from ::1: GET /.netlify/functions/hello
> Response with status 400 in 25 ms.

but after a few seconds the localhost server stops and the console returns

> Your lambda function took longer than 10 seconds to finish.
> If you need a longer execution time, you can increase the timeout using the -t or --timeout flag.
> Please note that default function invocation is 10 seconds, check our documentation for more > information (https://www.netlify.com/docs/functions/#custom-deployment-options).
> 
> events.js:173
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error [ERR_STREAM_WRITE_AFTER_END]: write after end
>     at write_ (_http_outgoing.js:584:17)
>     at ServerResponse.write (_http_outgoing.js:579:10)
>     at handleInvocationTimeout (/Git/mylocalrepository/node_modules/netlify-lambda/lib/serve.js:19:12)
>     at Timeout._onTimeout (/Git/mylocalrepository/node_modules/netlify-lambda/lib/serve.js:141:9)
>     at listOnTimeout (timers.js:327:15)
>     at processTimers (timers.js:271:5)
> Emitted 'error' event at:
>     at writeAfterEndNT (_http_outgoing.js:646:7)
>     at processTicksAndRejections (internal/process/next_tick.js:76:17)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

The function behind hello is the standard example from this repository (async/await version).

Any ideas?

**Comment by alexanderson1993** [comment]
I too am experiencing this issue, with a very simple function:

```javascript
exports.handler = async function(event, context) {
  return {
    statusCode: 200,
    body: "Hello, World"
  };
};
```
It has the same behavior with the `callback` parameter as well.

I believe this is related to this PR: https://github.com/netlify/netlify-lambda/pull/116

**Comment by alexanderson1993** [comment]
Digging in a bit, I think the issue is here: https://github.com/netlify/netlify-lambda/pull/116/files#diff-3288939317efd62bfc509440d662cacaR138

The `Promise.race` resolves, but never cancels the `setTimeout` call, so it still crashes even if the promise resolved properly.

I'll see about putting in a PR.

**Comment by sw-yx** [comment]
yikes, my bad. happy to take pr or if not i’ll fix ina couple hours

**Comment by alexanderson1993** [comment]
@sw-yx It's all good, I've already put in a PR. 👍

**Comment by sw-yx** [comment]
https://github.com/netlify/netlify-lambda/releases/tag/v1.4.1

**Comment by designbuedchen** [comment]
Amazing, thanks for the super fast fix!!!!!!!

**Comment by Aratramba** [comment]
I'm still experiencing the same issue with the new release (1.4.1).

**Comment by sw-yx** [comment]
Hi @Aratramba, thats not good. what node version are you running? i realized promise.finally is only supported in node 10. we may need to rewrite to avoid using promise.finally. 

i checked using https://github.com/netlify/create-react-app-lambda and i'm on node 10 and it works fine.

**Comment by sw-yx** [comment]
got rid of promise.finally with https://github.com/netlify/netlify-lambda/releases/tag/v1.4.2 cc @Aratramba

**Comment by Aratramba** [comment]
you're right, I am on an older Node version `8.11.2`. Both switching to Node 10 and updating to 1.4.2 solve this problem. Thanks!

**Comment by n1c01a5** [comment]
I have this issue wit node `v11` and netlify `1.4.2`.

**Comment by abtx** [comment]
I've got the same issue, every now and then the app crashes with 'write after end' error. I've got simple I/O functions on my Lamdas as well.
