### ISSUE TITLE
support locally for https 

### ISSUE THREAD

**Issue by kylemac** [netlify/netlify-lambda#126]
in some instances, like an oauth flow, it's mandatory for your callback URL to be HTTPS. since `lib/serve.js` is just an express app, would you consider supporting SSL locally? 

i'm not totally sure of the best DX but perhaps you specify the certs via a CLI flag/option...

```
netlify-lambda serve functions --ssl-key cert/server.key --ssl-cert cert/server.crt
```

**Comment by sw-yx** [comment]
PR welcome, but this isnt a priority for us right now. thanks for filing an issue

**Comment by kylemac** [comment]
sounds good. i'm happy to contribute but could you just give me any tips on getting the local version running?

```
cd netlify-lambda
yarn install
yarn run test
```

throws errors with object-spread error which means there's likely some babel setup that i'm not aware of. any tips?

**Comment by sw-yx** [comment]
keep alive
