### ISSUE TITLE
Deploying application without re-building with netlify-lambda

### ISSUE THREAD

**Issue by oyilmaztekin** [netlify/netlify-lambda#129]
Is there a way to serve the application without building with netlify. I've already configured everything in my **Nextjs** application with customizing the **webpack**.  It would be better if it can be served   on netlify just encapsulating the existing app with `serverless-http` script. 

There is a `yarn build`script which builds all the codebase and collects in `.next` folder. Normally the application is served in this folder via this script `NODE_ENV=production node server.js`. Is there a way to deploy this chunks to the netlify without rebuilding again.   

#### Project Structure
- components
- nested
- `lambdas`
  - server.js ( codes shared below )
- storybook
- netlify.toml
- ...
- server.js ( for dev )

**example lambda function**
**_lambda/server.js_**

```javascript
const express = require("express");
const next = require("next");
const serverless = require("serverless-http");
const port =
  parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });
const handle = app.getRequestHandler();

app.prepare().then(() => {
  const server = express();

  server.get("/", (req, res) => {
    return app.render(req, res, "/", req.query);
  });

  server.listen(port, err => {
    if (err) throw err;
    console.log(
      `> Ready on http://localhost:${port}`
    );
  });
});
module.exports.handler = serverless(app);
```

**Comment by sw-yx** [comment]
i'm not a Nextjs expert so pardon me that i dont fully understand your issue.. but if you are just deploying whatever is inside `.next`, yes you can just do `netlify deploy .next --prod` with the latest version of netlify CLI. you can also configure netlify.toml to do this and skip the build process.

**Comment by oyilmaztekin** [comment]
It is my bad. I didn't express myself. Serving the **.next** (or any other dist folder) wont be enough. This is not a static website and it needs to be served by a worker or a script. It is working as a `express.js` app because I am configuring the routes in backend and the `express.js` responsable for serving nextjs application. Also in **.next** folder, there is no `index.html` file except chunks javascript codes. Express.js processes the request came from the user and creates routes and sends static files to the browser nextjs created. I think the real problem of my circumstances I cannot solve how I can trigger or start to the express.js with corresponding script which is `NODE_ENV=production node server.js`. Maybe I didn't configure the lambas well. 

This is the structure of **.next** folder. 
- server
  - static
    - [deploy_hash_id]
      - pages
        - _app.js
        - index.js
        - about.js
        - etc...
- static
  - all client side codes...

**Comment by sw-yx** [comment]
then i am not sure this can be done without rebuilding.
