### ISSUE TITLE
Include binaries and other files

### ISSUE THREAD

**Issue by apmontgomery** [netlify/netlify-lambda#13]
Is it possible to include binaries and other files in the lambda folder?  I'm trying to include pdftk as described in this: https://lob.com/blog/aws-lambda-pdftk but don't see how to ensure that the ./bin folder is included in netlify-lambda

**Comment by sw-yx** [comment]
Hey Alex - apologies we never got back to you. It's been a while - did you ever figure this out? I am closing as stale for now - feel free to reopen if this is still relevant to you.

**Comment by kinduff** [comment]
Hello, would like to re-open this issue since I'm having issues setting up `node-canvas`. This package generates a binary (`canvas.node`) that is not being included as part of the dependencies (`node_modules`) in the lambda folder.

**Comment by sw-yx** [comment]
hey @kinduff, sorry for the delay, been a busy week for me. i suggest trying Netlify Dev
