### ISSUE TITLE
Mongodb connections never closed during development

### ISSUE THREAD

**Issue by svengau** [netlify/netlify-lambda#130]
Hi,

I've followed the [mongodb sample](https://docs.atlas.mongodb.com/best-practices-connecting-to-aws-lambda/) to use it with Lambda, and each time I update the code, the netlify-lambda server reloads the server, but the previously opened mongodb connection is not closed. 

So after a while, the mongodb server crashes because too many connections are opened.

I've already found a workaround, by using nodemon, which kills the netlify-lambda server and the associated mongodb connection, but I feel it could be cleaner if it could be handled directly by webpack.

Do you have any advice ?

Thanks for your help.

**Comment by sw-yx** [comment]
no idea. hope someone else here knows. also tagging @futuregerald in case he knows (he knows many things...)

**Comment by rendall** [comment]
How do you feel about closing the connection after use? Something like:

```
const getResults = async (id) => {
  const {client, collection} = await getClient()
  const objId = new ObjectId(id)
  const result = collection.find({}).toArray()
  client.close()
  return result  
}
```

// The main idea is to get the result and then close the connection before returning it. 
// but, for completeness, getClient is something like:

const getClient = () => new Promise((resolve, reject) => {
  const client = new MongoClient(URI, {useNewUrlParser:true})

  client.connect().then((client) => {
    const db = client.db(DB_NAME)
    const collection = db.collection(COLLECTION_NAME)

    resolve({client, db, collection})
  }).catch(reason => reject(reason))
})
```

**Comment by svengau** [comment]
@rendall thanks for the answer. I'm not a db expert, but from my understand, it's costy to open close a new connection for each request. Many articles advice to reuse opened connections across an application.

**Comment by rendall** [comment]
True, but it seems like the functions are opening new connections rather than reusing old ones, anyway, if I understood correctly?  How many queries hit the db at a usual peak hour?

**Comment by futuregerald** [comment]
In production,  you wouldn't necessarily close the connection since it can be re-used. I  have an example of this in https://github.com/futuregerald/functions-react-mongo/blob/master/src/lambda/post-user-details.js

You just want to check if it's still active and only create a new connection when you can't use the old one. Inn case you aren't aware, variables declared outside of the handler are cached by lambda. You can't account for it to always happen, but it does happen.

**Comment by svengau** [comment]
@rendall the problem appears only during development. In production everything works fine, the connections are reused.
@futuregerald indeed, in production I reuse the connection and it's ok. Thanks for your proposed workaround in dev mode, but it means having a different code between dev and production. I prefer using nodemon in this case.

Webpack hot reload is great on client side, and usually works straightforward. But on server side, from my understanding, the node process doesn't seem to be killed, and some objects are still remaining in memory (like db connections), leading to this kind of trouble.
