### ISSUE TITLE
installation instructions with -D flag

### ISSUE THREAD

**Issue by eatoncw** [netlify/netlify-lambda#131]
In your readme you have `yarn add -D netlify-lambda` - which installs it as a devDependency. This is different to the installation instructions on https://www.netlify.com/docs/functions/, and also doesn't work when building, as you get an error related to netlify-lambda command not found. 
Is this really meant to be a dev dependency?

**Comment by sw-yx** [comment]
good call. no, it is not. i'll remove that.
