### ISSUE TITLE
devDependencies error with bcrypt

### ISSUE THREAD

**Issue by jtparrett** [netlify/netlify-lambda#132]
Installing and then importing bcrypt with yarn/yarn workspaces gives the following errors. 

`Can't resolve 'aws-sdk'` - I believe this is listed as a devDependency for bcrypt, however netlify-lambda shouldn't care about this. I've experienced a similar thing with knex js also.

Any help would be very appreciated!

![image](https://user-images.githubusercontent.com/7426505/55486594-7b5cc700-5624-11e9-9bbd-48f14d2a8970.png)

**Comment by jtparrett** [comment]
Update: I have used bcryptjs instead for the time being!

**Comment by sw-yx** [comment]
if this is something to do with native modules.. that might be the reason... we are releasing something this week which may help with this, please stay tuned!

**Comment by brielov** [comment]
I have the same problem, I've replaced bcrypt with built in crypto module and netlify-lambda is complaining about `vue` dependency. I don't use vue-js in any way.
