### ISSUE TITLE
Parses Typescript .ts files as .js by default

### ISSUE THREAD

**Issue by rendall** [netlify/netlify-lambda#133]
My project has this file structure:
```
/project
  /function
  /function-src
     hello.ts
```
The `build` command is `tsc && netlify-lambda build functions-src`, which calls `tsc` (typescript compile command) and then `netlify-lambda`. In this way, `tsc` compiles `hello.ts` into a `hello.js` file which is then expected to be built by `netlify-lambda`. 

However, I get this error at the `netlify-lambda` step:

```
ERROR in ./hello.ts
Module build failed (from ../node_modules/babel-loader/lib/index.js):
SyntaxError: ...project\functions-src\hello.ts: Unexpected token, expected "," (1:29)

> 1 | export const handler = (event:any, context:any, callback:any) => {
```

While the `hello.js` file is handled properly, it appears that `netlify-lambda` is attempting to parse the `.ts` file.

I believe that this is an error. It should parse only `.js` files by default, and only parse `.ts` files with specific configuration. Barring this, there should be a way to exclude files in the configuration.

**Comment by sw-yx** [comment]
we are releasing something this week which may help you.

but i think you might simply be pointing `netlify-lambda` to the wrong folder. why not just point it to `/function` instead of `function-src`?

**Comment by rendall** [comment]
> but i think you might simply be pointing `netlify-lambda` to the wrong folder. why not just point it to `/function` instead of `function-src`?

When I do, I get an error saying explicitly not to do that:

```
netlify-lambda: Building functions
Error:
      netlify-lambda Error: Function source folder (specified in netlify-lambda serve/build command)
      and publish folder (specified in netlify.toml)
      should be different.
      For more info, check https://github.com/netlify/netlify-lambda#usage
```

I got it to work by restructuring my project into:

```
/project
  /function
  /function-src
  /ts
    /function-src
      hello.ts
```

and setting `outDir: "./"` and `rootDir: "./ts"` in `tsconfig.json`. Now the `tsc` step moves the compiled `hello.js` file into the `/project/function-src` to be handled by the next step. This avoids the problem because there is no `.ts' file in '/function-src' to confuse `netlify-lambda`

Thanks for your comment and I look forward to the new release!  Keep up the great work on this tool. Despite this hitch, `netlify-lambda` is extremely helpful.  Much respect.

**Comment by sw-yx** [comment]
ok so yes you can exclude TS by modifying the webpack config we ship for you: https://github.com/netlify/netlify-lambda/blob/4344f7e835f3d18ef2b4416375b2faea0908f747/lib/build.js#L80

write your webpack config overrides, and use the `-c` flag: https://github.com/netlify/netlify-lambda#webpack-configuration


btw our new release is https://www.netlify.com/products/dev/

**Comment by rendall** [comment]
Awesome!

**Comment by sw-yx** [comment]
closing unless any other needs :)

**Comment by rendall** [comment]
I fixed this by restructuring the project, but after creating another project, the issue still remains.  I consider it a bug.

The problem is that on `netlify-lambda serve` the `.ts` files are included in the build, and since they are not `.js` files, they throw an error.  They should either be properly parsed or ignored.

e.g. 
`ERROR in ./auth.ts
Module build failed (from .../jwt/node_modules/babel-loader/lib/index.js):
SyntaxError: ...\jwt\src\functions\auth.ts: Unexpected token (2:20)

  1 | import {Handler, Context, Callback} from 'aws-lambda'
> 2 | export const handler:Handler = (event, context:Context, callback:Callback) => {
    |                     ^
  3 | callback(null, {
  4 |   statusCode: 200,
  5 |   body: JSON.stringify({`

The unexpected token is `:`, which is part of Typescript syntax.  If `lambda-netlify` cannot parse `.ts` files, it should not even try.

**Comment by rendall** [comment]
@sw-yx Thanks for opening this issue again.  I created a repo to help you guys reproduce the error, which is here:  https://github.com/rendall/netlify-lambda--133

The instructions are in the `README`, but it's essentially just:
* clone it
* `npm install`
* verify that it's working first by `npm run serve` or `npm run build`
* reproduce the error by `npm run repro`

**Comment by sw-yx** [comment]
oh very nice! cant promise i'll take a look right now but appreciate the repro

**Comment by rendall** [comment]
No rush. I worked around the bug, so I'm not in a hurry.

**Comment by sw-yx** [comment]
never stale

**Comment by cellis** [comment]
@sw-yx  This is still kind of hard to understand for me. It seems this blocks me from writing netlify functions in Typescript, could you point to some documentation to do so?

**Comment by arimus** [comment]
For anyone else that hits this thread and runs into issues, I found that my issue was actually related to missing babel plugins.

```
  "devDependencies": {
    "@babel/preset-env": "^7.7.1",
    "@babel/preset-typescript": "^7.7.2",
    ...
```
and then this section after in the package.json:

```
  "babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-typescript"
    ]
  }
```

Now babel can actually correctly process the TS as such rather than trying to parse as JS.

**Comment by rendall** [comment]
Thank you! I suspected the solution involved webpack settings, which would
have sent me down the wrong path. Much appreciated.

**Comment by dorelljames** [comment]
> @sw-yx Any news about this error?



> For anyone else that hits this thread and runs into issues, I found that my issue was actually related to missing babel plugins.
> 
> ```
>   "devDependencies": {
>     "@babel/preset-env": "^7.7.1",
>     "@babel/preset-typescript": "^7.7.2",
>     ...
> ```
> 
> and then this section after in the package.json:
> 
> ```
>   "babel": {
>     "presets": [
>       "@babel/preset-env",
>       "@babel/preset-typescript"
>     ]
>   }
> ```
> 
> Now babel can actually correctly process the TS as such rather than trying to parse as JS.

I also have to add Babel plugin: `@babel/plugin-transform-runtime` and added it to `package.json` such as

```
"babel": {
    "presets": [
      "@babel/preset-env",
      "@babel/preset-typescript"
    ],
    "plugins": [
      [
        "@babel/transform-runtime"
      ]
    ]
}
```

**Comment by sw-yx** [comment]
i have left netlify and dont maintain this anymore, apols. but cheers
