### ISSUE TITLE
Unable to watch & reload correct files when using w/ Gatsby

### ISSUE THREAD

**Issue by ErisDS** [netlify/netlify-lambda#134]
Hi :wave:,

I've got a gatsby site setup and running, and I wanted to add a netlify function to proxy to a server-side-only API. After a lot of fiddling I managed to get it working, but netlify-lambda isn't watching the correct files.

Every time I run it, I get an error because of the `.eslintrc.js` file in the root dir. The functions load correctly, but if I make a change I have to stop and start manually.

The error:

```
Unhandled rejection Error: Cannot find module '/Users/hannah/Sites/HQ/functions/src/.eslintrc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
    at Object.clearCache (/Users/hannah/Sites/HQ/node_modules/netlify-lambda/lib/serve.js:191:36)
    at /Users/hannah/Sites/HQ/node_modules/netlify-lambda/bin/cmd.js:39:16
    at Array.forEach (<anonymous>)
    at Watching.handler (/Users/hannah/Sites/HQ/node_modules/netlify-lambda/bin/cmd.js:38:32)
    at compiler.hooks.done.callAsync (/Users/hannah/Sites/HQ/node_modules/netlify-lambda/node_modules/webpack/lib/Watching.js:98:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/hannah/Sites/HQ/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/hannah/Sites/HQ/node_modules/tapable/lib/Hook.js:154:20)
    at Watching._done (/Users/hannah/Sites/HQ/node_modules/netlify-lambda/node_modules/webpack/lib/Watching.js:97:28)
    at onCompiled (/Users/hannah/Sites/HQ/node_modules/netlify-lambda/node_modules/webpack/lib/Watching.js:47:18)
    at hooks.afterCompile.callAsync.err (/Users/hannah/Sites/HQ/node_modules/netlify-lambda/node_modules/webpack/lib/Compiler.js:630:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/hannah/Sites/HQ/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/hannah/Sites/HQ/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/Users/hannah/Sites/HQ/node_modules/netlify-lambda/node_modules/webpack/lib/Compiler.js:627:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/hannah/Sites/HQ/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
```

---

**Here's a full breakdown of my setup:**

My function is working and lives in `functions/src`, in the same repo as the gatbsy setup.

I added `netlify-lambda` as a dev dependency and because I am using dependencies from npm in my function, I also added `@netlify/zip-it-and-ship-it` as a dev dependency and made a little `zip.js` file that looks like this:

```
const { zipFunctions } = require(`@netlify/zip-it-and-ship-it`)
zipFunctions(`functions/src`, `functions/dist`)
```

In my package.json I have two yarn scripts:

```
  "zip": "node zip.js",
  "func": "netlify-lambda serve ./",
```

So `yarn func` will run netlify-lambda, and `yarn zip` will run my little zip script.

In my netlify.toml I have:

```
[build]
  command = "yarn zip && gatsby build"
  functions = "functions/src"

[context.production]
  functions = "functions/dist"
```

This is so that locally with `yarn func` the source file for the function gets used, and then on publish, it gets "zipped and shipped" to dist, and in production that package gets picked up.

----

**Alternative setups**

Maybe I've misunderstood something about how this is all meant to be used. I tried changing the netlify lambda command to:

`"func": "netlify-lambda serve ./functions/src",`

This is obviously wrong - the error message says "netlify-lambda Error: Function source folder (specified in netlify-lambda serve/build command)  and publish folder (specified in netlify.toml) should be different.

I also tried 

`"func": "netlify-lambda serve ./functions",`

Which gave me this message, which was promising:

```
---Start netlify-lambda notification---
      WARNING: No valid single functions files (ending in .mjs, .js or .ts) were found.
      This could be because you have nested them in a folder.
      If this is expected (e.g. you have a zipped function built somewhere else), you may ignore this.
      ---End netlify-lambda notification---
```

and then failed:

```
/Users/hannah/Sites/HQ/node_modules/netlify-lambda/node_modules/webpack/lib/webpack.js:31
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string]
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
    * configuration.entry should not be empty.
      -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
      -> An entry point without name. The string is resolved to a module which is loaded upon startup.
    * configuration.entry should be an array:
      [non-empty string]
```

and crashed...

So the original config is the only one that allows me to work on the function, but it doesn't work as expected. I've read as much documentation as I could find, would really appreciate some pointers!

**Comment by sw-yx** [comment]
hi! wow, long, detailed issue. great stuff! i unfortunately dont have ability to handle this today but @bcomnes is working on implementing zip-it-and-ship-it so you might be able to use our new [Netlify Dev](https://www.netlify.com/products/dev/) and not need `netlify-lambda` at all. Gimme a few days to respond on this, or if you need faster response, hit up our support at https://www.netlify.com/support/ with a link to this issue

**Comment by ErisDS** [comment]
FYI I've swapped my local env to use `netlify dev` instead of lambda, and asked a couple of questions about this on the forum: https://community.netlify.com/t/netlify-dev-functions-gatsby-ports-etc/448

`netlify dev` is fantastic. The functions server is reloading ❤️ 

What I'm still not sure of, and asked some questions about on the forum, is expectations in terms of config. This is what I have:

```
[build]
  command = "yarn zip && gatsby build"
  publish = "public/"
  functions = "functions/src"

[context.production]
  functions = "functions/dist"
```

This with my custom implementation of zip-it-and-ship-it works just fine. I assume if I were to use `netlify deploy` it would also work without the custom zipper (I will try this at some point). 

We are using github hooks to deploy though, and don't really want to change that. Therefore I assume at least for now I will always need my zip-it-and-ship-it thing?

**Comment by sw-yx** [comment]
for now this will work. ofc we (by we i mean Bret, above) are working hard to make it zero config.

**Comment by ErisDS** [comment]
Whoop no worries. Not trying to rush anyone - just checking I've understood what the expectations are and got the best available setup.

`netlify dev` is wicked, thanks for all the hard work!

**Comment by bcomnes** [comment]
Unbundled function deploys from the buildbot are now supported on the xenial image.  It will be backported to the trusty image soon in all likelihood.

**Comment by sw-yx** [comment]
git 'r done bret!

**Comment by ErisDS** [comment]
❤️ It works and it is beautiful ❤️ thank you @bcomnes 🙌

**Comment by bcomnes** [comment]
Trusty is live too now ✌️
