### ISSUE TITLE
Unable to see DEPLOY_PRIME_URL

### ISSUE THREAD

**Issue by nrm176** [netlify/netlify-lambda#145]
Hello,
I want to use DEPLOY_PRIME_URL on netlify lambda to change the behavior of a function depending on a url.  

I'm simply printing process.env.DEPLOY_PRIME_URL but it shows undefined. I am able to see my own environment variables.  Am I doing something wrong to access pre-defined variables? 

> Netlify has a number of pre-defined variables built in. Note that the variables listed are automatically set for your builds, and their values are not changeable.

**Comment by sw-yx** [comment]
that is only once deployed in production. netlify lambda is only for local dev. so you’ll have to supply your own env variables for local testing.
