### ISSUE TITLE
errorHandler leaks system user info to browser on base path and non-existent routes

### ISSUE THREAD

**Issue by jarrodoxical** [netlify/netlify-lambda#147]
The server leaks private info to the browser on basic usage. It should be easy and private to test on the open web without exposing the full error to the world.

> Request from ::ffff:1.111.111.57: GET /j
> Response with status 500 in 1 ms.
> Error during invocation:  { Error: Cannot find module '/home/USERNAME/PROJECT/functions/j'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
>     at Module.require (internal/modules/cjs/loader.js:636:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at /home/USERNAME/PROJECT/node_modules/netlify-lambda/lib/serve.js:111:17
>     at Layer.handle [as handle_request] (/home/USERNAME/PROJECT/node_modules/express/lib/router/layer.js:95:5)
>     at next (/home/USERNAME/PROJECT/node_modules/express/lib/router/route.js:137:13)
>     at next (/home/USERNAME/PROJECT/node_modules/express/lib/router/route.js:131:14)
>     at next (/home/USERNAME/PROJECT/node_modules/express/lib/router/route.js:131:14)
>     at next (/home/USERNAME/PROJECT/node_modules/express/lib/router/route.js:131:14) code: 'MODULE_NOT_FOUND' }

    

> Request from ::ffff:1.111.111.57: GET /
> Response with status 500 in 6 ms.
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
>     at assertPath (path.js:39:11)
>     at Object.join (path.js:1155:7)
>     at /home/USERNAME/PROJECT/node_modules/netlify-lambda/lib/serve.js:105:23
>     at Layer.handle [as handle_request] (/home/USERNAME/PROJECT/node_modules/express/lib/router/layer.js:95:5)
>     at next (/home/USERNAME/PROJECT/node_modules/express/lib/router/route.js:137:13)
>     at next (/home/USERNAME/PROJECT/node_modules/express/lib/router/route.js:131:14)
>     at next (/home/USERNAME/PROJECT/node_modules/express/lib/router/route.js:131:14)
>     at next (/home/USERNAME/PROJECT/node_modules/express/lib/router/route.js:131:14)
>     at next (/home/USERNAME/PROJECT/node_modules/express/lib/router/route.js:131:14)
>     at next (/home/USERNAME/PROJECT/node_modules/express/lib/router/route.js:131:14)

Here's the code I used to fix it.

```
function createHandler(dir, static, timeout) {
  return function(request, response) {
  ...
    if (dir==null || func==null) {
      handleErr(null,response);
      return;
    }
  ...
  }
}
```

```
function handleErr(err, response) {
  response.statusCode = 500;
  //response.write('Function invocation failed: ' + err.toString());
  response.write('Function invocation failed, check logs ');
  response.end();
  console.log('Error during invocation: ', err);
  return;
}
```

**Comment by sw-yx** [comment]
not sure i understand what is being leaked. netlify-lambda is for local dev testing, why and how are you "testing on the open web"?

in any case, PR welcome.

**Comment by jarrodoxical** [comment]
In my case a disperse team has a shared dev server exposed to the internet, for real world emulation I suppose. 

I didn't realize this is for local solo dev only. If that is the strict aim of the repo then my suggested changes probably don't cover all bases and won't be welcome.

**Comment by sw-yx** [comment]
you can use netlify-lambda build instead of serve then :)
