### ISSUE TITLE
Debugging help / using `--inspect` flag throws "error : unknown option"

### ISSUE THREAD

**Issue by madebycaliper** [netlify/netlify-lambda#148]
Hiya. I'm trying to configure VSCode to debug locally and after a couple hours searching and testing I'm opening this ticket and pausing so I can get some guidance. I've added the `webpack.functions.js` file and referenced it in my script command, but using the `--inspect` flag throws the error:

```
error: unknown option `--inspect'
error Command failed with exit code 1.
```
(I'm using yarn v1.9.4 and netlify-lambda v1.4.5)

Also, the Readme file has the following instructions but, unfortunately, I have _no clue_ what it means or how I would enable this:

> If using VSCode, it is likely that the `sourceMapPathOverrides` have to be adapted for breakpoints to work. 

I think there's an assumption that I would be a more seasoned re: Node + Webpack, but I personally don't have much at all. I'm using Netlify to deploy a Vue.js app that leverages Functions as an API layer, so I know the Vue ecosystem way better than Node/Webpack/Lambda.

Having clearer documentation around this would be *super* helpful. Thank you guys so much for working on this product!

**Comment by sw-yx** [comment]
hey! sorry you have so much trouble. that readme is mangled, that is my fault. it came from here https://github.com/netlify/netlify-lambda/pull/83 so @stefan-- may know better. i'll fix the readme.

as for you - what exactly are you trying to debug? lets get to the root cause here. are you trying to use a custom webpack config?

**Comment by madebycaliper** [comment]
Hey @sw-yx thanks for the quick reply. It would be awesome to have a little more clarity in the docs. In regards to what I'm debugging, it has to do with my actual functions app and not with netlify-lambda itself. console.logging only goes so far, and I'm dealing nested async try/catch statements which is kind of confusing to me. Any help would be appreciated.

**Comment by sw-yx** [comment]
i did fix the readme already https://github.com/netlify/netlify-lambda#debugging

hmm. if you can use `debugger` you may be able to step through your js. vscode offers extra help too.

- https://itnext.io/the-absolute-easiest-way-to-debug-node-js-with-vscode-2e02ef5b1bad
- https://code.visualstudio.com/docs/introvideos/debugging
