### ISSUE TITLE
Keeping local imports

### ISSUE THREAD

**Issue by thomasedwards** [netlify/netlify-lambda#149]
We’ve got a lot of functions now our site’s matured, coming up to 70. Each one has various re-used imports of things we’ve written.

The problem is that our Netlify Functions build or serve now can take over a minute to build. We’re not including `aws-sdk`, but we have a lot of other stuff we know doesn’t need to be dragged through Webpack 70 times.

Is there a way to keep local files from being bundled into the one file?

**Comment by sw-yx** [comment]
yes, you can use [Netlify Dev](https://github.com/netlify/netlify-dev-plugin/), which doesnt bundle at all. and then only selectively bundle stuff that needs bundling. make sense?

**Comment by thomasedwards** [comment]
Oh great! Will give it a whirl.
