### ISSUE TITLE
Deployments should fail when there are build errors

### ISSUE THREAD

**Issue by ericselin** [netlify/netlify-lambda#150]
### Current behavior

When `netlify-lambda build` has an error (due to an error from webpack), we end up with a deployment on Netlify with no functions (functions dir empty due to webpack build failing).

### Expected behavior

The whole deploy should fail.

### Reproduction

Create a simple function that doesn't build (e.g. syntax error or whatever) and deploy through Netlify CI/CD.

### Proposed solution

Add `bail: true` to the webpack configuration e.g. here: https://github.com/netlify/netlify-lambda/blob/7ab1220063bae096825d89ca02ebd8d760992cf9/lib/build.js#L111 This way, webpack returns a non-zero exit code when it has an error, and the deployment will fail. 

This is what I have done myself via the custom webpack config option, but I think it would be a pretty sensible default to have! 🙂

**Comment by sw-yx** [comment]
want to pr? :) great point.

**Comment by omonk** [comment]
@sw-yx just opened a PR here: https://github.com/netlify/netlify-lambda/pull/153

@ericselin, sorry I hope you don't mind. I came across this today and thought it would be very helpful to get this in.

**Comment by sw-yx** [comment]
released v1.4.8
