### ISSUE TITLE
Custom webpack config isn't loading

### ISSUE THREAD

**Issue by dalisoft** [netlify/netlify-lambda#161]
I tried with 
- `netlify-lambda serve functions --config webpack.config.netlify.js`
- `netlify-lambda serve functions -c webpack.config.netlify.js`
- `netlify-lambda serve --config webpack.config.netlify.js functions`
- `netlify-lambda serve -c webpack.config.netlify.js functions`
- `netlify-lambda serve functions --config ./webpack.config.netlify.js`
- `netlify-lambda serve functions -c ./webpack.config.netlify.js`
- `netlify-lambda serve --config ./webpack.config.netlify.js functions`
- `netlify-lambda serve -c ./webpack.config.netlify.js functions`

But none of them work, something wrong?

**Comment by ikoruk** [comment]
I also have this issue. It appears to be ignoring `--config` for `serve` but not for `build`

**Comment by ikoruk** [comment]
The problem seems to have been introduced in 1.4.10

**Comment by sw-yx** [comment]
hi! its my fault. i merged in a bad PR. the user came back to fix it: https://github.com/netlify/netlify-lambda/pull/159

so if you update to 1.4.13 it should work.

i ran this test: https://github.com/sw-yx/throwaway-test-netlify-lambda you can see the console.log come up from the custom webpack config

**Comment by dalisoft** [comment]
Thanks for fix
