### ISSUE TITLE
NODE_ENV is always "production" when running "netlify-lambda serve..."

### ISSUE THREAD

**Issue by rub1e** [netlify/netlify-lambda#163]
I've followed the **excellent** @sw-yx static/dynamic [tutorial](https://www.gatsbyjs.org/blog/2018-12-17-turning-the-static-dynamic/) and I'm trying to build on it to include _local_ env vars in development

I've set up a `.env.development` file and I'm trying to use `NODE_ENV` to set the correct `.env` filepath in development.

But when I run the start scripts (`gatsby develop` and `netlify-lambda serve src/lambda`), I get two different `NODE_ENV`s :confused: 

* In `gatsby-config.js` it logs "development" 
* In `src/lambda/hello.js` it logs "production" :face_with_head_bandage: 

Apologies if this is obvious / expected behaviour, but I've run out of ideas :confounded:

**Comment by sw-yx** [comment]
hmm. what version are you on? we addressed this here https://github.com/netlify/netlify-lambda/issues/119 may just need an update

**Comment by rub1e** [comment]
I'm on **1.4.13**

I did see #123 from #119 but that fix is for `build`, whereas the issue I'm having is with `serve`

I've tried going through https://github.com/netlify/netlify-lambda/blob/master/lib/serve.js but I can't figure out why this would be. Happy to do a PR if you can point me in the right direction!

**Comment by sw-yx** [comment]
i'm not sure either. dont have time to go through this in detail right now. if you have the time, this one should be a matter of placing a few strategic console.log's inside your `netlify-lambda` instance to figure out where your `NODE_ENV` is getting introduced.
