### ISSUE TITLE
Webpack entrypoint collection and warning is assuming a default set of file extensions

### ISSUE THREAD

**Issue by mohsen1** [netlify/netlify-lambda#164]
even if I extend the webpack config with more extensions, entry files are not picked up. I believe default `.wasm` extension is not supported here either:

https://github.com/netlify/netlify-lambda/blob/80bcdd851c47a999c425d6a47e6731d0f5f1af9e/lib/build.js#L115-L124

**Comment by sw-yx** [comment]
ok. what new regex are you proposing?

**Comment by mohsen1** [comment]
after you merged webpack configs, construct a regex from config.resolve.extensions list

**Comment by sw-yx** [comment]
pr welcome!
