### ISSUE TITLE
Can serve typescript functions locally but build fails when deploying to netlify, what am I missing?

### ISSUE THREAD

**Issue by BaronBeans** [netlify/netlify-lambda#165]
4:18:27 PM: Build ready to start
4:18:30 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
4:18:30 PM: build-image tag: v3.3.2
4:18:30 PM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
4:18:30 PM: Fetching cached dependencies
4:18:30 PM: Starting to download cache of 255.0KB
4:18:30 PM: Finished downloading cache in 81.718871ms
4:18:30 PM: Starting to extract cache
4:18:30 PM: Failed to fetch cache, continuing with build
4:18:30 PM: Starting to prepare the repo for build
4:18:31 PM: No cached dependencies found. Cloning fresh repo
4:18:31 PM: git clone https://github.com/BaronBeans/proofofconcept
4:18:34 PM: Preparing Git Reference refs/heads/master
4:18:35 PM: Found netlify.toml. Overriding site configuration
4:18:35 PM: Different functions path detected, going to use the one specified in the toml file: 'lambda' versus '' in the site
4:18:35 PM: Creating functions prep folder
4:18:35 PM: Starting build script
4:18:35 PM: Installing dependencies
4:18:37 PM: Downloading and installing node v10.16.0...
4:18:37 PM: Downloading https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-x64.tar.xz...
4:18:37 PM: #
4:18:37 PM: #
4:18:37 PM:   3.0%
4:18:37 PM: 
###################################
4:18:37 PM:                              49.1%
4:18:37 PM: 
#############################################
4:18:37 PM: ########################### 100.0%
4:18:37 PM: Computing checksum with sha256sum
4:18:38 PM: Checksums matched!
4:18:41 PM: Now using node v10.16.0 (npm v6.9.0)
4:18:41 PM: Attempting ruby version 2.6.2, read from environment
4:18:42 PM: Using ruby version 2.6.2
4:18:43 PM: Using PHP version 5.6
4:18:43 PM: Started restoring cached node modules
4:18:43 PM: Finished restoring cached node modules
4:18:43 PM: Installing NPM modules using NPM version 6.9.0
4:19:14 PM: > core-js@2.6.9 postinstall /opt/build/repo/app/node_modules/babel-runtime/node_modules/core-js
4:19:14 PM: > node scripts/postinstall || echo "ignore"
4:19:14 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
4:19:14 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
4:19:14 PM: > https://opencollective.com/core-js 
4:19:14 PM: > https://www.patreon.com/zloirock 
4:19:14 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
4:19:14 PM: > core-js-pure@3.1.4 postinstall /opt/build/repo/app/node_modules/core-js-pure
4:19:14 PM: > node scripts/postinstall || echo "ignore"
4:19:14 PM: Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
4:19:14 PM: The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
4:19:14 PM: > https://opencollective.com/core-js 
4:19:14 PM: > https://www.patreon.com/zloirock 
4:19:14 PM: Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
4:19:16 PM: npm
4:19:16 PM:  WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/jest-haste-map/node_modules/fsevents):
4:19:16 PM: npm WARN
4:19:16 PM:  notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
4:19:16 PM: npm
4:19:16 PM:  WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/chokidar/node_modules/fsevents):
4:19:16 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
4:19:16 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.6 (node_modules/fsevents):
4:19:16 PM: npm WARN
4:19:16 PM:  notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
4:19:21 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
4:19:16 PM: added 1419 packages from 766 contributors and audited 902032 packages in 32.38s
4:19:16 PM: found 0 vulnerabilities
4:19:16 PM: NPM modules installed
4:19:17 PM: Started restoring cached go cache
4:19:17 PM: Finished restoring cached go cache
4:19:17 PM: unset GOOS;
4:19:17 PM: unset GOARCH;
4:19:17 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
4:19:17 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";

**Comment by BaronBeans** [comment]
This is a create-react-app --typescript with .babelrc file, netlify.toml file... function worked when it was .js now it has been changed to .ts it has removed it from the functions page on netlify and build is failing:
"failed during stage 'building site': Build script returned non-zero exit code: 1"

**Comment by sw-yx** [comment]
i dont see the build error here. what happens when you run your build command locally?

**Comment by BaronBeans** [comment]
Create-react-app builds fine locally, it's only when it's running on netlify that it fails

**Comment by BaronBeans** [comment]
I just wanted to check there wasn't another step I was missing to get it working in production, as you can see I've set this up as a test project to make sure the concept works the function itself is the same as the hello world example

**Comment by BaronBeans** [comment]
OK seems to be working now, I'm not sure if it was because npm was down, or if deleting node_modules and package-lock and running npm install has fixed... site is now deploying and building successfully, but functions do not exist, suspect this is incorrect path in netlify.toml so closing this issue.

**Comment by sw-yx** [comment]
indeed npm was down for a while becuase of cloudflare. 🤷🏼‍♂️ as always feel free to reopen if you need anything
