### ISSUE TITLE
JavaScript heap out of memory Error

### ISSUE THREAD

**Issue by BrianSHenderson** [netlify/netlify-lambda#168]
Is there a maximum size for the size of the functions that can be used?

When I use:
npx netlify-lambda serve ./functions

I am getting: 
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by sw-yx** [comment]
yes, but this heap issue may be due to leaky code. particularly cause the function is being run on your local machine. can you investigate the callstack?

**Comment by sw-yx** [comment]
in production it's 1024mb https://www.netlify.com/docs/functions/#custom-deployment-options
