### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by asselstine** [netlify/netlify-lambda#17]
I followed the tutorial exactly:

1. `yarn add netlify-lambda` in a new directory
2. create a file called 'netlify.toml' with the contents 
```toml
[build]
  functions = "functions"
```
3. created the file `src/hello.js` with the contents:
```javascript
exports.handler = function(event, context, callback) {
    callback(null, {
    statusCode: 200,
    body: "Hello, World"
    });
}
```
4. Ran `netlify-lambda serve src` and got:

```
Unhandled rejection Error: Cannot find module '<redacted>/functions/hello'
```

Am I missing something here?

**Comment by asselstine** [comment]
FYI babel-core was installed, but it was the wrong version.  I had to install babel-core separately:

```
yarn add @babel/core@^7.0.0
```

**Comment by fool** [comment]
I think this was probably caused by https://github.com/netlify/netlify-lambda/issues/20
