### ISSUE TITLE
Referencing JSX files

### ISSUE THREAD

**Issue by sonicsmith** [netlify/netlify-lambda#176]
I'm having issues trying to serve / build my functions when they reference any of my React code.
I want to be able to do this so that I can convert a react component to an svg and pass the data down as a raw svg string.
When I try to reference a function within a JSX file, I get:
```
Module parse failed: Unexpected token (9:4)
You may need an appropriate loader to handle this file type.
```

Thanks!

**Comment by sw-yx** [comment]
you need babel to transpile your jsx down. read the readme for how to add a babelrc

**Comment by sonicsmith** [comment]
I'm still getting the problem even after setting this `.babel` at the root:
```
{
  "presets": ["@babel/preset-react", "@babel/preset-env"],
  "plugins": [
    "@babel/plugin-transform-react-jsx",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-object-assign",
    "@babel/plugin-proposal-object-rest-spread"
  ]
}
```
I am using an (unejected) "create react" project if that makes a difference.
Are there other dependencies I need to install as well?

**Comment by sonicsmith** [comment]
For anyone who find this later. I found the issue.
I was trying to access other files in my project using my function file. I expected the netlify-lambda babel compiler to transpile them all, but yea, fixed it by just putting all needed code in the function file.
