### ISSUE TITLE
Can't resolve 'bufferutil' and 'utf-8-validate'

### ISSUE THREAD

**Issue by NickyMeuleman** [netlify/netlify-lambda#179]
on `netlify-lambda build`
```
WARNING in /home/nicky/projects/jason-api/node_modules/subscriptions-transport-ws/node_modules/ws/lib/buffer-util.js
not found: Error: Can't resolve 'bufferutil' in '/home/nicky/projects/jason-api/node_modules/subscriptions-transport-ws/node_modules/ws/lib'

WARNING in /home/nicky/projects/jason-api/node_modules/subscriptions-transport-ws/node_modules/ws/lib/validation.js
not found: Error: Can't resolve 'utf-8-validate' in '/home/nicky/projects/jason-api/node_modules/subscriptions-transport-ws/node_modules/ws/lib'
```

Despite those errors, ./netlify/functions/graphql still works locally after running `netlify-lambda serve`

The repo I'm having this issue in is also the mininal reproduction https://github.com/NickyMeuleman/jason-api

**Comment by glennreyes** [comment]
This can be solved by configuring your [webpack externals](https://github.com/netlify/netlify-lambda#webpack-configuration):

```js
//./config/webpack.functions.js
const nodeExternals = require('webpack-node-externals');

module.exports = {
  externals: [nodeExternals()],
};
```

However, imho it is more reasonable to have this set up by default so there's no hassle with a custom webpack config when setting up a graphql lambda.

@sw-yx Any thoughts or objections on having this config by default? I'd be happy to open a PR adding it!

**Comment by glennreyes** [comment]
One thing I forgot to note, you'll also have to point to your config file in the `netlify-lambda` command, eg:

```sh
netlify-lambda build src/lambda --config webpack.functions.js
```

**Comment by NickyMeuleman** [comment]
Thanks so much for this!
Didn't make the connection I would need this.
I swear I read the `README` when swapping from netlify dev to netlify lambda...briefly 😊

**Comment by PavelMGs** [comment]
If you facing this problem with Next.JS, you just need to add isServer condition for it gonna work
`if (isServer) {
  config.externals = [nodeExternals()]
}`

**Comment by PavelMGs** [comment]
If you facing this problem with Next.JS, you just need to add isServer condition for it gonna work

`if (isServer) { config.externals = [nodeExternals()] }`

**Comment by dquanghuy4444** [comment]
> If you facing this problem with Next.JS, you just need to add isServer condition for it gonna work
> 
> `if (isServer) { config.externals = [nodeExternals()] }`

hi there , could u public your file , i have problem with nextjs

**Comment by PavelMGs** [comment]
> > If you facing this problem with Next.JS, you just need to add isServer condition for it gonna work
> > `if (isServer) { config.externals = [nodeExternals()] }`
> 
> hi there , could u public your file , i have problem with nextjs

I cant do it because of NDA, sorry. You can just show your config

**Comment by dquanghuy4444** [comment]
> > > If you facing this problem with Next.JS, you just need to add isServer condition for it gonna work
> > > `if (isServer) { config.externals = [nodeExternals()] }`
> > 
> > 
> > hi there , could u public your file , i have problem with nextjs
> 
> @dquanghuy4444 I cant do it because of NDA, sorry. You can just show your config

thank bro , i install fabricjs (https://www.npmjs.com/package/fabric) , and deploy nextjs by netlify and i have this error 
7:57:31 PM: ModuleNotFoundError: Module not found: Error: Can't resolve 'bufferutil' in '/opt/build/repo/node_modules/ws/lib'
7:57:31 PM: > Build error occurred
7:57:31 PM: Error: > Build failed because of webpack errors
7:57:31 PM:     at /opt/build/repo/node_modules/next/dist/build/index.js:15:924
7:57:31 PM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:6:584)

My next.config.js
const path = require("path")

const withSass = require("@zeit/next-sass")
const nodeExternals = require("webpack-node-externals")

module.exports = withSass({
    /* bydefault config  option Read For More Optios
     here https://github.com/vercel/next-plugins/tree/master/packages/next-sass*/

    cssModules: true
})

module.exports = {
    /* Add Your Scss File Folder Path Here */
    sassOptions: {
        includePaths: [path.join(__dirname, "styles")]
    }
}

module.exports = {
    productionBrowserSourceMaps: false
}

module.exports = {
    webpack: (config, { isServer }) => {
        // eslint-disable-next-line space-before-blocks
        if (isServer) {
            config.externals = nodeExternals()
        }

        return config
    }
}

module.exports = {
    images: {
        domains: ["cdn.shopify.com"]
    }
}

**Comment by Jesuspinarte** [comment]
The solution for me was add this ti my `next.config.js`:

```
const nodeExternals = require('webpack-node-externals');

const nextConfig = {
  reactStrictMode: true,
};

module.exports = {
  ...nextConfig,
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.externals = [nodeExternals()];
    }

    return config;
  },
};
```
I'm using Next 12.1.5

**Comment by ThatGuySam** [comment]
`external_node_modules` for `netlify.toml` is supposed to fix this but for some reason, it wouldn't work, however, when I tried including the node_module paths that fixed it. 

```
// netlify.toml
[functions]
...
  included_files = [
    # For some reason this works to fix "bufferutil" error on
    # Netlify Function and external_node_modules does not
    "node_modules/bufferutil/**", 
    "node_modules/utf-8-validate/**"
  ]
...
```

**Comment by irzko** [comment]
module.exports = {
  ...nextConfig,
  webpack: (
    config,
    { buildId, dev, isServer, defaultLoaders, nextRuntime, webpack }
  ) => {
    // Important: return the modified config
    if (isServer) {
      config.externals.push({
        bufferutil: "bufferutil",
        "utf-8-validate": "utf-8-validate",
      });
    }
    return config;
  },
};

**Comment by irzko** [comment]
`module.exports = {
  ...nextConfig,
  webpack: (
    config,
    { buildId, dev, isServer, defaultLoaders, nextRuntime, webpack }
  ) => {
    // Important: return the modified config
    if (isServer) {
      config.externals.push({
        bufferutil: "bufferutil",
        "utf-8-validate": "utf-8-validate",
      });
    }
    return config;
  },
};`

**Comment by szRadik** [comment]
next version 13.4.7

`npm i bufferutil@4.0.7 --save-dev`
`npm i utf-8-validate@5.0.10 --save-dev`
`npm i supports-color@8.1.1 --save-dev`


// next.config.js

```
const nextConfig = {
  reactStrictMode: true,
};

module.exports = {
  ...nextConfig,
  webpack: (config, { isServer }) => {
    if (!isServer) {
      config.externals.push({ bufferutil: "bufferutil", "utf-8-validate": "utf-8-validate", "supports-color": "supports-color" }); 
    }

    return config;
  },
};

```

**Comment by naingaungphyo** [comment]
> next version 13.4.7
> 
> `npm i bufferutil@4.0.7 --save-dev` `npm i utf-8-validate@5.0.10 --save-dev` `npm i supports-color@8.1.1 --save-dev`
> 
> // next.config.js
> 
> ```
> const nextConfig = {
>   reactStrictMode: true,
> };
> 
> module.exports = {
>   ...nextConfig,
>   webpack: (config, { isServer }) => {
>     if (!isServer) {
>       config.externals.push({ bufferutil: "bufferutil", "utf-8-validate": "utf-8-validate", "supports-color": "supports-color" }); 
>     }
> 
>     return config;
>   },
> };
> ```

I have no idea what those packages are used for. Can someone clarify it please?

And my another concern is that don't we need those packages in production as we are installing with dev flag? Is not that something Nextjs needs to handle internally for their config?

**Comment by xalteropsx** [comment]
what is for nuxt ?

**Comment by muckee** [comment]
I solved this by adding the following `.yarnrc.yml` file in the project root directory:
```yaml
nodeLinker: pnp
pnpMode: loose
```
