### ISSUE TITLE
Issue parsing multipart/form-data

### ISSUE THREAD

**Issue by dmmulroy** [netlify/netlify-lambda#180]
I'm trying to parse multipart/form-data with `busboy`(specifically images)  and are running into similar issues as listed in this thread: https://github.com/mscdex/busboy/issues/199. I'm not 100% sure that this is a `netlify-lambda` issue, but I am using the same `busboy` code on an express server and it works fine.

Summary of that issue:

> This is not a busboy issue, you just need to enable binary support in API Gateway (https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-console.html)

If I can help in anyway, let me know - whether that is providing more detail or diving in (though not sure where) and submitting a PR.

Also linking to my community issue for visibility in case this isn't a repo issues: https://community.netlify.com/t/functions-issues-parsing-images-from-multipart-form-data/3068

**Comment by ryanditjia** [comment]
Also running into the same issue, I wrote about it asking for support in AWS subreddit:
https://www.reddit.com/r/aws/comments/d23ff8/need_help_with_lambda_formdata_nodemailer/
