### ISSUE TITLE
Blog post using Netlify Functions in Elm

### ISSUE THREAD

**Issue by ceddlyburge** [netlify/netlify-lambda#182]
Hi There

The readme suggests submitting inspirational example usages of Netlify Functions as issues, and there is nothing I have found on the internet about using Elm with Netlify functions yet.

So here is the one I wrote.

https://www.freecodecamp.org/news/how-to-use-netlify-functions-in-elm/

Cheers, Cedd

**Comment by DavidWells** [comment]
This is super cool. Thanks @ceddlyburge 

I'm gonna add this to https://functions.netlify.com/tutorials

**Comment by ceddlyburge** [comment]
Awesome, thanks! Let me know if you want me to do anything ...

**Comment by DavidWells** [comment]
Boom live on https://functions.netlify.com/tutorials

Thanks again!

**Comment by ceddlyburge** [comment]
Amazing! Thanks!
