### ISSUE TITLE
netlify functions:create creates a dir that fails on build

### ISSUE THREAD

**Issue by rptrainor** [netlify/netlify-lambda#185]
Building Gatsby and Netlify Lambda with `js-fauna-graphql` backend.  But all I did was `netlify functions:create` then `git push`, and the build has failed on multiple attempts.  This is all from the code generated on `netlify functions:create`.  I have not changed any of the generated code, and the build still fails, so I thought I was log the issue here.

The build logs show:

> Error: Could not find "apollo-server-lambda" module in file: /backend/backend.js

And the schema.graphql file is missing from the build dir in /functions/

here is the build log form the failed build & the `/functions/myGeneratedDir/package.json`

![Screen Shot 2019-09-04 at 4 54 36 PM](https://user-images.githubusercontent.com/12374439/64301646-b85f1980-cf34-11e9-92d0-501faabce35a.png)

3:58:13 PM: Build ready to start
3:58:15 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
3:58:15 PM: build-image tag: v3.3.2
3:58:15 PM: buildbot version: c78d626072f493c5e920f1da6e930a88f3a7d230
3:58:15 PM: Fetching cached dependencies
3:58:15 PM: Starting to download cache of 150.7MB
3:58:18 PM: Finished downloading cache in 2.806635395s
3:58:18 PM: Starting to extract cache
3:58:25 PM: Finished extracting cache in 7.228888074s
3:58:25 PM: Finished fetching cache in 10.184985116s
3:58:25 PM: Starting to prepare the repo for build
3:58:26 PM: Preparing Git Reference refs/heads/master
3:58:26 PM: Found netlify.toml. Overriding site configuration
3:58:26 PM: Different functions path detected, going to use the one specified in the toml file: 'functions' versus '' in the site
3:58:26 PM: Creating functions prep folder
3:58:26 PM: Starting build script
3:58:26 PM: Installing dependencies
3:58:27 PM: Started restoring cached node version
3:58:30 PM: Finished restoring cached node version
3:58:31 PM: v10.16.3 is already installed.
3:58:32 PM: Now using node v10.16.3 (npm v6.9.0)
3:58:32 PM: Attempting ruby version 2.6.2, read from environment
3:58:34 PM: Using ruby version 2.6.2
3:58:34 PM: Using PHP version 5.6
3:58:34 PM: Started restoring cached node modules
3:58:34 PM: Finished restoring cached node modules
3:58:34 PM: Started restoring cached yarn cache
3:58:34 PM: Finished restoring cached yarn cache
3:58:35 PM: Installing NPM modules using Yarn version 1.17.0
3:58:36 PM: yarn install v1.17.0
3:58:37 PM: [1/4] Resolving packages...
3:58:37 PM: success Already up-to-date.
3:58:37 PM: Done in 1.14s.
3:58:38 PM: NPM modules installed using Yarn
3:58:38 PM: Started restoring cached go cache
3:58:38 PM: Finished restoring cached go cache
3:58:38 PM: unset GOOS;
3:58:38 PM: unset GOARCH;
3:58:38 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
3:58:38 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
3:58:38 PM: go version >&2;
3:58:38 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
3:58:38 PM: go version go1.12 linux/amd64
3:58:38 PM: Installing missing commands
3:58:38 PM: Verify run directory
3:58:38 PM: Executing user command: yarn build
3:58:38 PM: yarn run v1.17.0
3:58:38 PM: $ gatsby build
3:58:41 PM: success open and validate gatsby-configs — 0.125
3:58:42 PM: success load plugins — 0.790
3:58:42 PM: success onPreInit — 0.029
3:58:42 PM: success delete html and css files from previous builds — 0.032
3:58:42 PM: success initialize cache — 0.027
3:58:42 PM: success copy gatsby files — 0.071
3:58:42 PM: success onPreBootstrap — 0.030
3:58:43 PM: success source and transform nodes — 0.179
3:58:43 PM: success Add explicit types — 0.022
3:58:43 PM: success Add inferred types — 0.194
3:58:43 PM: success Processing types — 0.141
3:58:43 PM: success building schema — 0.422
3:58:43 PM: success createPages — 0.026
3:58:43 PM: success createPagesStatefully — 0.110
3:58:43 PM: success onPreExtractQueries — 0.026
3:58:43 PM: success update schema — 0.055
3:58:44 PM: success extract queries from components — 0.378
3:58:44 PM: success write out requires — 0.029
3:58:44 PM: success write out redirect data — 0.020
3:58:44 PM: success Build manifest and related icons — 0.304
3:58:44 PM: success onPostBootstrap — 0.331
3:58:44 PM: info bootstrap finished - 5.628 s
3:58:44 PM: success run static queries — 0.025
3:58:52 PM: success Building production JavaScript and CSS bundles — 8.337
3:58:53 PM: success Rewriting compilation hashes — 0.095
3:58:53 PM: success run page queries — 0.098 — 3/3 190.48 queries/second
3:58:54 PM: success Building static HTML for pages — 1.242 — 3/3 11.91 pages/second
3:58:54 PM: info Done building in 15.617 sec
3:58:54 PM: Done in 16.13s.
3:58:55 PM: Function Dir: /opt/build/repo/functions
3:58:55 PM: TempDir: /tmp/zisi-5d70418545319d00084fc6a3
3:58:55 PM: Prepping functions with zip-it-and-ship-it 0.3.1
3:58:56 PM: Error: Could not find "apollo-server-lambda" module in file: /backend/backend.js.
3:58:56 PM: Please ensure "apollo-server-lambda" is installed in the project.
3:58:56 PM: Error prepping functions
3:58:56 PM: Error running command: Build script returned non-zero exit code: 1
3:58:56 PM: Failing build: Failed to build site
3:58:56 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
3:58:56 PM: Finished processing build request in 41.003958241s

**Comment by DavidWells** [comment]
Hey @rptrainor 

When the deploy happens the functions folder is missing the dependancies. Make sure they are installed in there.

You can do this with:

- https://community.netlify.com/t/new-install-command-added-to-netlify-lambda-v1-6-0/2766
- or https://community.netlify.com/t/functions-and-node-modules/2323/6

Pretty soon, we will automatically install the deps if they are missing but we don't have that feature just yet

**Comment by sw-yx** [comment]
we should also print a better warning. while we wait for build bot to be a thing.

**Comment by rptrainor** [comment]
Thank you @DavidWells and @sw-yx adding the `"postinstall": "netlify-lambda install",` solved it.
