### ISSUE TITLE
`.babelrc` should be looked up in parent directories

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-lambda#188]
At the moment, the `.babelrc` is only looked up in the current directory. However I think `babel/loader` forwards the `babelrc` option to `babel`, which then looks up any babel configuration file. So the current logic might consider the user has no Babel configuration, even though they do. 

This is especially likely inside monorepos.

Another issue is that Babel configurations can also be called `babel.config.js`, `.babelrc.js` or be a `babel` property inside `package.json`.

Checking the parent directories would be easy to implement (e.g. using [`find-up`](https://github.com/sindresorhus/find-up)). 

A more proper way might be to use the `@babel/core` package though, and use [their methods](https://babeljs.io/docs/en/babel-core#advanced-apis) to check if there's a Babel configuration.

**Comment by erezrokah** [comment]
Fixed via https://github.com/netlify/netlify-lambda/pull/364
