### ISSUE TITLE
The current `.babelrc` lookup logic does not work on Windows

### ISSUE THREAD

**Issue by ehmicky** [netlify/netlify-lambda#189]
When the current directory does not find any `.babelrc`, the directory passed as input is used searched instead. There might two issues with the current logic:
  1) the lookup starts with the ancestor, where it probably should start with the descendant
  2) the lookup relies on the path delimiter being `/`. This does not work on Windows.

#188 would solve both problems.

**Comment by aimee-gm** [comment]
A work-around here is to use a [custom webpack configuration](https://github.com/netlify/netlify-lambda#webpack-configuration).

For example: 

`webpack.functions.js`
```js
module.exports = {
  module: {
    rules: [
      {
        test: /\.ts?$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/preset-typescript", "@babel/preset-env"],
          },
        },
      },
    ],
  },
};
```
and run `netlify-lambda build <path_to_fn_folder> --config ./webpack.functions.js`
