### ISSUE TITLE
@types/aws-lambda are not in sync with identity object

### ISSUE THREAD

**Issue by andrew-secret** [netlify/netlify-lambda#193]
I'm not 100% sure if this is an issue or I'm just too dump.. But I bootstrap my app with CRA + Typescript with `netlify-lambda` and I want to make an request with an `authorization` header...

Like this:

```tsx
    if (user.token) {
      fetch("/.netlify/functions/some-webhook", {
        headers: {
          Authorization: `Bearer ${user.token.access_token}`
        }
      }).then(response => console.log(response));
    }
```

now I add logging to my lambda and I can see this object structure here:

```tsx
context { identity:
   { url: 'NETLIFY_LAMBDA_LOCALLY_EMULATED_IDENTITY_URL',
     token: 'NETLIFY_LAMBDA_LOCALLY_EMULATED_IDENTITY_TOKEN' },
  user:
   { exp: 1567894522,
     sub: 'some crazy numbers 123123123',
     email: 'some@email.com',
     app_metadata: { provider: 'email', roles: [Array] },
     user_metadata: { full_name: 'Random Name' } } }
```

As far as I understood it is recommended to consume the `@types/aws-lambda` to get proper types for my lambda function. But I recognized that the types doesn't cover this object structure I receive in my terminal..

Instead I got this:
```d.ts
export interface Context {
    ...
    identity?: CognitoIdentity;
    clientContext?: ClientContext;
    ...
}

export interface CognitoIdentity {
    cognitoIdentityId: string;
    cognitoIdentityPoolId: string;
}

```

**Comment by sw-yx** [comment]
correct. you’ll have to extend the standard types with the extra stuff that netlify provides for you (this is actually a nice to have, turst me). unfortunately i never got around to documenting it. but basically you’ll just want to extend your types like this
https://github.com/typescript-cheatsheets/react-typescript-cheatsheet/blob/master/ADVANCED.md#working-with-non-typescript-libraries-writing-your-own-indexdts

**Comment by sw-yx** [comment]
i’ll take a pr to add this to the docs once youre done

**Comment by andrew-secret** [comment]
Oh man thank u for your quick reply 👍
