### ISSUE TITLE
AWS_LAMBDA_JS_RUNTIME is not being used when set through netlify.toml

### ISSUE THREAD

**Issue by miteyema** [netlify/netlify-lambda#198]
Hi

When I try to set `AWS_LAMBDA_JS_RUNTIME = "nodejs10.x"` in `netlify.toml` (as per  https://docs.netlify.com/functions/build-with-javascript/#runtime-settings) and use `netlify-lambda build <folder>` to build my functions, `v8.10.0` is still being used for building by Netlify.

- Repo on https://github.com/miteyema/aws-serverless-nodejs10
- Result on https://aws-serverless-nodejs10.netlify.com/.netlify/functions/version

How does this happen? Am I missing something?

**Update**: when I set AWS_LAMBDA_JS_RUNTIME through the user interface (via https://app.netlify.com/sites/YOUR-PROJECT-NAME/settings/deploys#environment-variables), it does work. So why doesn't it work when I set it through netlify.toml ?

@ehmicky I saw your related issue https://github.com/netlify/netlify-lambda/issues/186, but I don't know if this applies to my situation, could you have a look at it? Many thanks!

**Comment by miteyema** [comment]
Update: when I set `AWS_LAMBDA_JS_RUNTIME` through the user interface (via https://app.netlify.com/sites/YOUR-PROJECT-NAME/settings/deploys#environment-variables), it does work.
So why doesn't it work when I set it through `netlify.toml` ?

**Comment by bpinto** [comment]
I had the same issue. Any updates about this bug?

**Comment by miteyema** [comment]
Yes, this was the reply from Netlify Support:

> We only read environment variables from our UI for functions, not from netlify.toml.

**Comment by ehmicky** [comment]
@miteyema Sorry for not answering earlier, I am not maintaining this specific project and did not see my name tagged.

Glad you found a workaround, but I would like to understand your initial issue to make we're solving it.

When you say:

```js
v8.10.0 is still being used for building by Netlify.
```

Are you talking about the Node.js version used:
  - build-time (by `netlify-lambda`)?
  - or runtime (when calling the function via HTTP)?

**Comment by miteyema** [comment]
@ehmicky Indeed, I formulated that incorrectly, I meant at the runtime.
Please see the following file in my repo:

https://github.com/miteyema/aws-serverless-nodejs10/blob/5d5cffc81a3b5fc6e1ac7d35d654f99567682f28/lambda/version.js#L5

**Comment by ehmicky** [comment]
I might be mistaken but I believe this problem might not be related to `netlify-lambda` (which bundles your Functions) but with Netlify infrastructure (which uploads the bundled Functions to AWS Lambda).

@rybit @smoya @kitop what do you think?

**Comment by kitop** [comment]
@ehmicky I think you're right. Will investigate further.

**Comment by erquhart** [comment]
Still unresolved.

**Comment by lloydh** [comment]
See also https://github.com/netlify/netlify-lambda/pull/222 which expands ``netlify-lambda``s runtime matching to include 12.x
