### ISSUE TITLE
Node js

### ISSUE THREAD

**Issue by Ravibabuc** [netlify/netlify-lambda#199]
C:\Program Files\nodejs\node_app_test>node Server.js
<!doctype html>
<html lang="en">

<head>
    <title>Hello, world!</title>
</head>

<body>
    <h1>Hello, world!</h1>
</body>

</html>
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:594:17)
    at ServerResponse.write (_http_outgoing.js:586:15)
    at C:\Program Files\nodejs\node_app_test\Server.js:17:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:649:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}

C:\Program Files\nodejs\node_app_test>

----------------------Above error i am getting for below code on line "     response.write(data);		"
what may be the issue

function onRequest(request, response) {
  //  response.writeHead(200, { 'Content-Type': 'text/html' });

   fs.readFile('index.html', null, function (error, data) {
    if (error) {
        response.writeHead(404, {'Content-Type': 'text/html'});

        respone.write('Whoops! File not found!');
        console.log(error.stack);
        return;
     }
     response.writeHead(200, {'Content-Type': 'text/html'});	

     response.write(data);		

     console.log(data.toString());
    });
   // response.write("helloworld")
    response.end();
}

http.createServer(onRequest).listen(8081);

**Comment by abtx** [comment]
Hi, having same issue here. Have you found a solution?
