### ISSUE TITLE
.babelrc.js ignored

### ISSUE THREAD

**Issue by jeysal** [netlify/netlify-lambda#200]
The `.babelrc` filename is hardcoded in https://github.com/netlify/netlify-lambda/blob/d9f70def3f569616c4a0fb659f627e0b0cfd6000/lib/build.js#L18-L30, meaning that alternatives such as `.babelrc.js` are ignored.
Ideally Babel's own config resolution should be used instead of reimplementing it so errors like this cannot happen.

**Comment by Robin-Hoodie** [comment]
Just bumped into this as well, I'm up for opening a PR on this

**Comment by erezrokah** [comment]
Thanks @Robin-Hoodie a PR would be great 🙌
