### ISSUE TITLE
Webpack config stats has no effect

### ISSUE THREAD

**Issue by svengau** [netlify/netlify-lambda#204]
Hi, 

the `stats` config in webpack could not be configured, because it's hardcoded in the code:

```

console.log(stats.toString({ color: true }));
```

For example, I would like to remove some noisy warnings with the following config, but it's not possible:

```
  stats: {
    warningsFilter: [
      /Critical dependency: the request of a dependency is an expression/,
      /Critical dependency: require function is used in a way in which dependencies cannot be statically extracted/
    ],
  },
```

Thanks.

[edit]: [Here is the list](https://webpack.js.org/configuration/stats/) of all parameters of the toString(...) function.

**Comment by svengau** [comment]
I've proposed a PR: https://github.com/netlify/netlify-lambda/pull/205

**Comment by kevinmarrec** [comment]
Just encountered the same issue, I wanted to set `stats.entrypoints` to `false` but doesn't seem indeed possible.

**Comment by svengau** [comment]
Hi @markus-willems and sorry to bother you. I'm not sure about the issue review workflow on this repo. Would it be possible to have a feedback on this issue from the Netlify team ? Thanks.

**Comment by markus-willems** [comment]
Hey @svengau. Don't worry, all good! Unfortunately, I am not affiliated with the fine people of Netlify. That be Shawn (@sw-yx) for example. Good luck with your issue.

**Comment by sw-yx** [comment]
thanks for the ping. i dont really maintain this anymore. i'll merge this tho
