### ISSUE TITLE
Types not being checked for TypeScript

### ISSUE THREAD

**Issue by PabloRomanH** [netlify/netlify-lambda#208]
Both netlify-lambda build and netlify-lambda serve don't seem to be verifying the types of TypeScript code. I tried it with the example project sw-yx/create-react-app-lambda-typescript, and something as simple as `let a: number = 'abc'` doesn't trigger any warnings. Is it a problem with netlify-lambda or with the example project?

**Comment by mraerino** [comment]
Since most projects (even create-react-app itself) uses the typescript babel preset nowadays, the story is like this:
- Babel will only strip type definitions, not do a typecheck
- You can run `tsc --noEmit` to do a typecheck

I'd recommend having a npm script like `npm run typecheck` that does `tsc --noEmit` and call that as part of your build.

**Comment by PabloRomanH** [comment]
Adding it to an npm script wouldn't work with netlify-lambda serve, right? I would lose the autoreload functionality if I'm not mistaken.
Should we add full TypeScript support to netlify-lambda?
What's the plan for adding TypeScript support to netlify dev?

**Comment by mraerino** [comment]
i think there are plans to integrate serving bundled functions better with `netlify dev` directly, and then deprecating this tool. There might be place to make sure typescript support is :100: when that happens.
Create-React-App uses the eslint-typescript integration to do this on the fly, I think. This way it's easy to check js and ts projects by just having some conditions for the eslint config. I guess we might be adapting that at some point.

I'd recommend you already adopt `netlify dev` so you can take advantage of this in the future.
Netlify Dev will run your `netlify-lambda build` command every time anything changes: https://cli.netlify.com/netlify-dev#function-builders-function-builder-detection-and-relationship-with-netlify-lambda

It should be possible to also define a task that runs typescript with the watch flag `-w` which will run on every code change and output warnings. Using npm-run-all you can combine that with your main build command.

**Comment by PabloRomanH** [comment]
It's great if I can use netlify dev.
But I don't quite get where the call to tsc should go. I have npm-run-all. Changes to the TypeScript code are detected and the functions are being autoreloaded.
If I have this in the scripts section of my project.json, tsc doesn't run:
```
    "build": "run-p build:**",
    "build:app": "react-scripts build",
    "build:lambda": "netlify-lambda build src/lambda",
    "build:lambdatypecheck": "tsc -w --noEmit src/lambda",
```

This gives an error:
```
    "build": "run-p build:**",
    "build:app": "react-scripts build",
    "build:lambda": "netlify-lambda build src/lambda; tsc --noEmit src/lambda",
```

With this it never finishes launching the app:
```
    "build": "run-p build:**",
    "build:app": "react-scripts build",
    "build:lambda": "netlify-lambda build src/lambda; tsc --noEmit -w src/lambda",
```

Where do I put the tsc command?

**Comment by mraerino** [comment]
this is turning into very specific advice about your particular project.
Can i ask you to go to community.netlify.com and ask there?

1. there are other netlify users who might be able to help you
2. our support folks try to help in most cases (no guarantee)

**Comment by PabloRomanH** [comment]
Okay, I'll ask at the Netlify Community.
Nothing here is specific about my project though. I'm just trying to get TypeScript working properly in the sample project that's referenced in the docs as the way to get TypeScript working with netlify-lambda.
