### ISSUE TITLE
Using HTML template in the same folder as js function file

### ISSUE THREAD

**Issue by step135** [netlify/netlify-lambda#221]
Having files `functions/template.html` and `/index.js` fails when `index.js` wants to read it.

a) `dirname=process.cwd()`
b) `dirname=__dirname`

`fs.readdir(path.resolve(dirname, 'template.html'), function (err, f) {})`

What is the solution or workaround?

**Comment by matt-peck** [comment]
I'm trying to use Express View Engines with Netlify Functions and I'm running into an issue that is similar. I can't seem to figure out how to bundle static views folder with the lambda function so that it can be found during invocation.

**Comment by step135** [comment]
Why anyone on Netlify answer neither after nearly half an year?
