### ISSUE TITLE
migrate to node v8.10 runtime

### ISSUE THREAD

**Issue by leonardodino** [netlify/netlify-lambda#23]
[it just became available on aws!](https://aws.amazon.com/blogs/compute/node-js-8-10-runtime-now-available-in-aws-lambda/)

<sub>i know this repo is only for the transpiling and bundling step, but i don't know where else to keep track of this issue...</sub>

**Comment by verythorough** [comment]
It's now on Netlify, too! 🎉 

https://www.netlify.com/blog/2018/04/03/node.js-8.10-now-available-in-netlify-functions/
