### ISSUE TITLE
What's the status on this project ?

### ISSUE THREAD

**Issue by svengau** [netlify/netlify-lambda#237]
Hi Netlify, 

the last version has been published in August, 2019, and there is a bunch of merged PRs since. 

Would it be possible to publish a new version, so we can use those PRs ? 
And / or if the project is kind of deprecated, could you add a note about it, and eventually a migration procedure to follow ?

Thanks

**Comment by svengau** [comment]
Hi @kitop, you are the last one who has done a merge, so question for you. ;-)

There're a lot of new commits since the last version, published in August, 2019. Do you think it's possible to publish a new version on this project ?

**Comment by kitop** [comment]
I'm not an active maintainer of this. Pinged internally to see who can take it.

**Comment by erezrokah** [comment]
@svengau  please see https://github.com/netlify/netlify-lambda/issues/240.
Sorry for the very long delay!

**Comment by erezrokah** [comment]
Released the new version https://github.com/netlify/netlify-lambda/releases/tag/v2.0.0
