### ISSUE TITLE
How to properly type my netlify-lambda functions?  payloadFormatVersion

### ISSUE THREAD

**Issue by dev-b01** [netlify/netlify-lambda#238]
After adding type definitions with https://www.npmjs.com/package/@types/aws-lambda 

I noticed AWS has payloadFormatVersion 1.0 or 2.0

![Screenshot 2020-06-26 at 14 23 50](https://user-images.githubusercontent.com/61806563/85856665-b367a100-b7b8-11ea-95a2-1aab08dafb64.png)

What version does Netlify use? 

Thank you!

**Comment by erezrokah** [comment]
Hi @dev-b01 and sorry for the late response.
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/3eff5b53d4aaffff945399c14f5ff2bd80f29266/types/aws-lambda/trigger/api-gateway-proxy.d.ts#L20
and https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

`APIGatewayProxyHandlerV2` is for the HTTP APIs integrations with lambda.
You should use `APIGatewayProxyHandler`.
