### ISSUE TITLE
Cannot invoke function while deployed, local version runs fine

### ISSUE THREAD

**Issue by Lav-Hinsu** [netlify/netlify-lambda#257]
i can run and test that the function runs locally, but it cannot run on netlify. it stops with this error
ERROR	(node:8) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

i do not use Buffer() anywhere in my code. it must be in either of the following dependencies i use in this way
import axios from "axios";
import qs from "qs"; 
require("encoding");

my node version is 14.5.0
i also set the deployment node version in deployment and settings using the environment variable
NODE_VERSION. it is set to 14.5.0

is there a way i can just suppress / ignore the warning? am i missing something?

**Comment by Lav-Hinsu** [comment]
it was a problem with one of the libraries i was importing, in the end i ended up just using fetch

**Comment by erezrokah** [comment]
Thanks for following up @Lav-Hinsu !
