### ISSUE TITLE
Handlers that serve images results in 500

### ISSUE THREAD

**Issue by asselstine** [netlify/netlify-lambda#26]
A 500 results when creating a handler that writes an image buffer to the output:

```javascript
exports.handler = function (event, context, callback) {

var outputBuffer = // ... image buffer stuff

var response = {
    statusCode: 200,
    headers: {'Content-Type' : 'image/png'},
    body: outputBuffer.toString('base64'),
    isBase64Encoded: true
}

callback(null, response)

}
```

**Comment by fool** [comment]
(note that this works in production when run on AWS - just breaks in netlify-lambda!)

**Comment by sw-yx** [comment]
i have no idea how to fix this.. just gonna say help wanted / PR welcome

**Comment by 8eecf0d2** [comment]
@asselstine if you need a patch, #68 seems to have fixed this but is still waiting on review...

**Comment by 8eecf0d2** [comment]
@sw-yx Below is the snippet I tested, the `base64` package `netlify-lambda` is using seems to be incorrectly decoding the string - not sure if this is an issue with the package or with usage.

```js
import * as fs from "fs";

export const handler = async (request, context, callback) => {
  const pngBuffer = fs.readFileSync(path.join(process.cwd(), "image.png"));
  
  return {
    statusCode: 200,
    body: pngBuffer.toString("base64"),
    isBase64Encoded: true,
  }
}
```

**Comment by sw-yx** [comment]
will get to this soon

**Comment by sw-yx** [comment]
woo hoo it worked! 
![image](https://user-images.githubusercontent.com/6764957/48104244-7b78a800-e1e7-11e8-8388-22aed0a78865.png)

you seriously rock @8eecf0d2. wondering if i can convince the other Netlify folk to just give you commit rights...

**Comment by sw-yx** [comment]
@asselstine please retry.. with netlify-lambda v1.0.3 and something like this as a lambda function:

```js
import * as fs from 'fs'
import path from 'path'

export const handler = async (request, context, callback) => {
  const path2 = path.join(process.cwd(), 'image.png')
  const pngBuffer = fs.readFileSync(path2)

  return {
    statusCode: 200,
    headers: { 'Content-Type': 'image/png' },
    body: pngBuffer.toString('base64'),
    isBase64Encoded: true,
  }
}
```

correctly returned the image for me

**Comment by asmockler** [comment]
👋 sorry if this isn't the right place to ask, but I can't seem to find anywhere more relevant.

I ran into this issue and am trying to get it to work using the above solution, but I can't seem to get `image.png` to exist when I deploy to netlify. Is there a place i should be placing or copying my static assets to during build? When I `console.log(fs.readdirSync(process.cwd()));`, all I see is the name of my JS file, not the images I copy into that directory 🤔 

Any guidance would be very much appreciated!

**Comment by sw-yx** [comment]
i mean all we do is deploy static assets... if you have a “build” or “public” folder that you serve the rest of your files from like index.html. in any case open a diff issue, this is unrelated it seems

**Comment by sw-yx** [comment]
also feel free to send in a support request since yours seems to be a netlify deployment rather than netlify-lambda question

**Comment by asselstine** [comment]
Thanks @8eecf0d2 and @sw-yx!  That code has long been off my radar but I bet you fixed it.

**Comment by isaurav0** [comment]
This issue still exists for golang.
