### ISSUE TITLE
bash: netlify-lambda: command not found

### ISSUE THREAD

**Issue by kildareflare** [netlify/netlify-lambda#27]
Installed netlify-lambda into project directory using npm 
`npm install netlify-lambda`

But when I try to use it:
`netlify-lambda serve <folder>`

I see
`bash: netlify-lambda: command not found`

I've also tried in a windows command prompt

Windows 10
Node: v8.9.1
NPM: v5.4.2

**Comment by fool** [comment]
This is the same as any other node module - you'll need to have it in your path to run it :)

This stackoverflow post has more details:  https://stackoverflow.com/questions/9679932/how-to-use-package-installed-locally-in-node-modules
