### ISSUE TITLE
Separate functions folder into build folder and src folder, And specify package manager.

### ISSUE THREAD

**Issue by peter-wd-1** [netlify/netlify-lambda#276]
**Is your feature request related to a problem? Please describe.**

Have two requests:
1. **To Separate functions folder into build folder and src folder**
I have lambda functions that have their own dependency and so need to use `netlify-lambda install` and It only detects **build** folder(relatively designated functions folder becomes build folder because there is no way to specify it as src folder). If I want to separate src folder and build folder for functions, I need to specify `netlify-lambda install <folder>` and I can't install with just one line of the script. Instead, I need to specify all the lambda functions folder with the install command. I think this is very handful way of installing functions. I really can't think of use case that `netlify-lambda install` would not need to check all lambda folders and install each dependency(Users love convenience as we all know).  

2. **To Specify package manager.**
Seems like there is no way to specify the package manager. But for the nested dependency issue I want to use `yarn` instead.
https://github.com/netlify/netlify-lambda/blob/fd4b65f758d7ce2a0ba1e50bdc86b3840d8a51d0/lib/install.js#L7

**Describe the solution you'd like**

In `netlify.toml`, 
```
functions-src = "./src/functions"
functions-build = "./functions-build"
```

With just one line of code for installing dependency of all functions in `package.json`.
```
"scripts":{
  "postinstall": "netlify-lambda install",
}
```

Thank you,

**Comment by erezrokah** [comment]
Hi @peter-wd-1, thank you for opening this.
Do you mind separating the issue into 2 different issues so we can have a separate discussion per feature request?
I have thoughts on both requests, but it might get confusing to convey them in the same issue thread.

**Comment by peter-wd-1** [comment]
Sure, Then I'll close this request.
