### ISSUE TITLE
Web3 support in functions

### ISSUE THREAD

**Issue by thisisvilla** [netlify/netlify-lambda#33]
Currently, including the web3 library for netlify functions causes errors.

The hang up seems to be installing web3's dependencies. There seems to be a fix for using lambda directly, here: https://ethereum.stackexchange.com/questions/41870/how-can-i-requireweb3-on-amazon-aws-lambda/42024#42024 - but it doesnt work on netlify. 

Hopefully netlify can support this dependency! 

Thanks! :)

**Comment by depadiernos** [comment]
This issue is related to https://app.intercom.io/a/apps/q245f50x/inbox/inbox/1479299/conversations/16054870817 (internal ticket)
