### ISSUE TITLE
Use .babelrc in function folder first

### ISSUE THREAD

**Issue by niicojs** [netlify/netlify-lambda#34]
Would be nice if .babelrc is first looked (or only looked?) into the folder of the functions.
Root folder may contains .babelrc used by other part of the project.

**Comment by iiroj** [comment]
You could also override the default loader in Webpack and supply custom [options](https://babeljs.io/docs/en/babel-core/#options) to [babel-loader](https://github.com/babel/babel-loader):

```javascript
module.exports = {
    module: {
      rules: [
        {
          test: /\.js?$/,
          exclude: /(node_modules|bower_components)/,
          use: {
            loader: "babel-loader",
            options: {
              babelrc: false,
              ...myCustomOptions
          }
        }
      ]
    }
}
```

**Comment by sw-yx** [comment]
hi @huygn  - netlify-lambda uses babel 7 now so hopefully less issues there.

thanks everyone
