### ISSUE TITLE
refactor: switch to async I/O

### ISSUE THREAD

**Issue by erezrokah** [netlify/netlify-lambda#365]
It would be nice to switch to async I/O which should allow for some performance optimizations.
See https://github.com/netlify/netlify-lambda/blob/0b365ee067182675fb1a25349f5889e1ee37ac02/lib/config.js#L7
and https://github.com/netlify/netlify-lambda/blob/master/lib/build.js

**Comment by Alucard17** [comment]
@erezrokah Can I take this issue?
