### ISSUE TITLE
Adding additional webpack loaders

### ISSUE THREAD

**Issue by abusedmedia** [netlify/netlify-lambda#37]
Hi there

I'm trying to compile a function, that uses a soap module, with netlify-lambda without success, giving me the following warning:
```
WARNING in ./lambda-test/node_modules/ejs/lib/ejs.js
require.extensions is not supported by webpack. Use a loader instead.
```

I know that it's possible to add additional webpack loaders, that is what I tried to do using https://github.com/bazilio91/ejs-compiled-loader but I cannot sort it out.

Any hints from your side?
Many thanks

**Comment by alekseyBatuhtin** [comment]
I've the same problem.

**Comment by sw-yx** [comment]
hi both - can you check this issue for how to add aditional webpack loaders: https://github.com/netlify/netlify-lambda/issues/64

if that doesnt help pls feel free to open a new issue and i'll take a look.
