### ISSUE TITLE
netlify-lambda build does not seem to copy non-js file

### ISSUE THREAD

**Issue by testn** [netlify/netlify-lambda#374]
**Describe the bug**
netlify-lambda build does not seem to copy non-js file. Let's say I have

```sh
/src/lambda/function.js
/src/lambda/data.csv
```

**Expected behavior**
I should be able to access /src/lambda/data.csv using something like

```
const fileName = "./data.csv"
const resolved = (process.env.LAMBDA_TASK_ROOT)? path.resolve(process.env.LAMBDA_TASK_ROOT, fileName):path.resolve(__dirname, fileName)
```

but it looks like data.csv does not exist in build-lambda directory

**Screenshots**
N/A

**Desktop (please complete the following information):**
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 3.21 GB / 15.85 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    netlify-lambda: ^1.4.5 => 1.6.3
```
**Additional context**

**Comment by erezrokah** [comment]
Hi @testn, you should be able to achieve that via a [custom webpack](https://github.com/netlify/netlify-lambda#webpack-configuration) config and https://webpack.js.org/plugins/copy-webpack-plugin/.

I'm not sure yet if there is a default value we should provide here.

**Comment by testn** [comment]
Can't we configure netlify-lambda to copy non-js files?

**Comment by erezrokah** [comment]
> Can't we configure netlify-lambda to copy non-js files?

Hi @testn the current way to configure it is via a custom webpack config, e.g.

In `webpack.functions.js`
```js
const CopyPlugin = require("copy-webpack-plugin");

module.exports = {
  plugins: [
    new CopyPlugin({
      patterns: [
        { from: "source", to: "dest" }
      ],
    }),
  ],
};
```

Then `netlify-lambda serve --config ./webpack.functions.js`

**Comment by bartosjiri** [comment]
You can also achieve this by combining bundled functions & zipped functions approaches.

At the moment, netlify-lambda is bundling your JS function, not including the asset/non-JS file, and deploying only the single JS file - this is the bundled approach. If you want more control over what is being deployed, I suggest the zipped approach. You can read more about both in this official [netlify-lambda deploy examples repository](https://github.com/netlify/function-deploy-test).

Here are the steps I took when I was tackling a similar problem:
1) Add a conditional path to the file in the JS function 
    *- you have already done this through the `process.env.LAMBDA_TASK_ROOT` check*
2) Bundle the function using the regular `netlify-lambda build <path/to/lambda/source/folder>` command
3) Copy your assets/non-JS files to the lambda deploy folder 
    *- the location should be defined in the `netlify.toml` as `functions` value*
4) Zip all contents of this deploy folder
    *- name of the zip file should be the same as the name of the JS lambda*
5) Delete all files & folders in the deploy folder except the zip file
    *- if there is still the bundled JS file, it will be deployed instead of our zip file*

And here are scripts I use to do all of this:
```
"build": "<your-other-build-commands> && npm run build:lambda",
"build:lambda": "netlify-lambda build <path/to/lambda/source/folder> && npm run lambda:zip",
"lambda:zip": "cp -r <path/to/assets> <path/to/lambda/deploy/folder>;  cd <path/to/lambda/deploy/folder>; zip -r <lambda-name>.zip .; find . ! -name <lambda-name>.zip -delete",
```

Personally, I prefer this over the custom webpack config and/or additional `package.json`, but it may be applicable only for specific use cases.
