### ISSUE TITLE
Netlify lambda function query string parameters are passed in different way between local environment and production envionment

### ISSUE THREAD

**Issue by DarkPonyBee** [netlify/netlify-lambda#409]
**Describe the bug**

I created several lambda functions and deployed them on the Netlify service.

I passed several queries via GET request, locally they passed as an array but once it is deployed they passed as a string.

**To Reproduce**

lambda function side:

```js
export const handler = constructNetlifyHandler({
  get: async (event, context, postgrest) => {
    console.log(event.queryStringParameters);

    return await getAllTasks(
        postgrest,
        event.queryStringParameters,
        event.loggedInUserOrg
    );
  },
});

```

postman side:

```
{{host}}/tasks?orgUid=06ea7872-32eb-4e7a-ba45-63e2b9e6c747&statusUid=ba92a0b7-2e80-4cd2-8d37-fa18d5ca22b9&statusUid=78dcdbe1-007a-493a-ad94-50a0ec613d0d&statusUid=1cbc65b8-831d-4cba-a1ad-111a0757e76b
```

Logs on local environment:

```
{
  orgUid: '06ea7872-32eb-4e7a-ba45-63e2b9e6c747',
  statusUid: [
    'ba92a0b7-2e80-4cd2-8d37-fa18d5ca22b9',
    '78dcdbe1-007a-493a-ad94-50a0ec613d0d',
    '1cbc65b8-831d-4cba-a1ad-111a0757e76b'
  ]
}
```

Logs on netlify production envionment:

```
{
  orgUid: '06ea7872-32eb-4e7a-ba45-63e2b9e6c747',
  statusUid: 'ba92a0b7-2e80-4cd2-8d37-fa18d5ca22b9, 78dcdbe1-007a-493a-ad94-50a0ec613d0d, 1cbc65b8-831d-4cba-a1ad-111a0757e76b'
}
```

**Expected behavior**

In both environments, query params are passed in the same way. (as an array of strings or as a string)

**Screenshots**

Postman side:
![image](https://user-images.githubusercontent.com/68030494/114247195-83157b80-9962-11eb-90cc-304a0bacd12f.png)

Logs on local environment:

![image](https://user-images.githubusercontent.com/68030494/114247239-9fb1b380-9962-11eb-96ff-cb818c859785.png)

Logs on production environment:

![image](https://user-images.githubusercontent.com/68030494/114247271-b48e4700-9962-11eb-8454-a5c4c468a6e2.png)

**Desktop (please complete the following information):**
Run the following command `npx envinfo --system --binaries --npmPackages netlify-lambda` and attach the output

**Additional context**

```
 System:
    OS: macOS 11.2.3
    CPU: (4) x64 Intel(R) Core(TM) i3-9100 CPU @ 3.60GHz
    Memory: 54.82 MB / 24.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.20.1 - ~/.nvm/versions/node/v12.20.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - ~/.nvm/versions/node/v12.20.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    netlify-lambda: ^2.0.3 => 2.0.3 
```

**Comment by erezrokah** [comment]
Hi @DarkPonyBee, are you using the `netlify-lambda serve` command?
If so, see https://github.com/netlify/netlify-lambda#netlify-lambda-serve-legacy-command about it being a legacy command.

Can you try this out with `netlify dev`? See more [here](https://github.com/netlify/netlify-lambda#when-to-use-netlify-dev-or-netlify-lambda-or-both)

**Comment by erezrokah** [comment]
Closing this per https://github.com/netlify/netlify-lambda/issues/409#issuecomment-817539691. If still relevant please comment on the issue
