### ISSUE TITLE
Upgrade to webpack 5

### ISSUE THREAD

**Issue by chrbala** [netlify/netlify-lambda#423]
**Is your feature request related to a problem? Please describe.**
The most recent version of ts-loader [does not work on Webpack 4](https://github.com/TypeStrong/ts-loader/issues/595#issuecomment-824240989).

**Describe the solution you'd like**
Upgrade to Webpack 5

**Describe alternatives you've considered**
Only use older versions of webpack plugins that work with Webpack 4.

**Additional context**
This is a breaking change, so it should be a major version upgrade to netlify-lambda.

**Comment by erezrokah** [comment]
Hi @chrbala, while we consider this feature request, I recommend trying out our new `esbuild` based bundler:
https://www.netlify.com/blog/2021/04/02/modern-faster-netlify-functions/
as it supports TypeScript and new ECMAScript features out of the box (I'm assuming that's the reason you're using `netlify-lambda`).

**Comment by bpinto** [comment]
I'd love to see support for webpack 5 as well.

I believe gatsby v3 requires webpack 5. So using a different tool (esbuild) when using netlify + gatsby might not be ideal.

Is there an existing work for making this project webpack 5 compatible?

**Comment by arsinclair** [comment]
Any update here? It's all very quiet.
