### ISSUE TITLE
Bug in uploading file

### ISSUE THREAD

**Issue by NithinIBhandari1999** [netlify/netlify-lambda#433]
Hi Netlify Teams,
I was testing serverless functions and while testing file upload in local machine it is not working but when i uploaded this to netlify , the file upload started working, so I believe that there is some problem in package netlify-lambda.

Thank you.

**Comment by erezrokah** [comment]
Hi @NithinIBhandari1999, can you please follow the [issue template](https://github.com/netlify/netlify-lambda/issues/new?assignees=&labels=type%3A+bug&template=bug_report.md&title=) and provide a reproduction scenario?

It's very hard to figure out the underlying issue without one.

**Comment by NithinIBhandari1999** [comment]
**Describe the bug**:
When we upload image to serverless backend which is running in Local Environment, the file is not uploading correctly (file has extra bytes).

Note: I am uploading the file and its size is 185247 bytes and file name is HelloWorld.pdf.

Example when uploading a file from windows (I dont known why **file has extra bytes** so I believe that the package netlify-lambda has some error ):
{
        "name": "HelloWorld.pdf",
        "size": 335857
}

When we upload image to serverless backend which is deployed on netlify backend, the file is uploading correctly.
{
        "name": "HelloWorld.pdf",
        "size": 185247
}

**To Reproduce**
1) Create a express serverless netlify lamda funtion and run it by "netlify-lambda serve src" server and create a route to uploadFile (http://localhost:9000/.netlify/functions/server/uploadFile).
2) Then upload the file from your local environment (that is your laptop or pc) to uploadFile route, you will see that there is difference of bytes from the uploaded file.
3) Deploy the backend to netlify functions and then upload File route, You will see that there is no difference of bytes from the uploaded file (that means that file is uploaded correctly).

**Expected behavior:**
When uploading the file from Local Environment the size of the file upload should be same.

For example:
Here in Local Environment, when i upload the file which has size 185247 bytes 
1) In windows it is showing it as 335857 bytes (basically the file is not uploading properly)
2) In netlify server (where i deployed serverless lamda) it is showing it as 185247 bytes (That is correct).

**Desktop Info**:
System:
  OS: Windows 10 10.0.19042
  CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
  Memory: 1.33 GB / 7.80 GB
Binaries:
  Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
  Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
  npm: 7.7.5 - C:\Program Files\nodejs\npm.CMD
npmPackages:
  netlify-lambda: ^2.0.7 => 2.0.7

**Comment by erezrokah** [comment]
Hi @NithinIBhandari1999, `netlify-lambda serve` command is deprecated, see https://github.com/netlify/netlify-lambda#netlify-lambda-serve-legacy-command.

Have you tried using `netlify dev`? See https://cli.netlify.com/commands/dev/

**Comment by NithinIBhandari1999** [comment]
I have created an public repo regarding the error:
Repo Link: https://github.com/NithinIBhandari1999/netlify-file-upload-test
Netlify Link: https://netlify-file-upload-test.netlify.app/

**Comment by erezrokah** [comment]
Hi @NithinIBhandari1999, thank you for the public repo. Does the issue reproduce with `netlify dev`?

**Comment by NithinIBhandari1999** [comment]
Yes, the Issue reproduced with netlify dev.

**Comment by danez** [comment]
I just tested this in the linked repository:

- I removed `netlify-lambda` and `netlify` packages
- Updated all other packages to their latest version including all subdependencies (removed package-lock.json before npm install)
- run `netlify dev` in the project
- uploaded the file and got the correct result.

If you still encounter this report here: https://github.com/netlify/cli
