### ISSUE TITLE
Invocations should time out in 10s

### ISSUE THREAD

**Issue by michaek** [netlify/netlify-lambda#45]
Since production functions [time out in 10 seconds](https://www.netlify.com/docs/functions/#custom-deployment-options) it would probably be a big help for local function development if netlify-lambda also timed out in 10 seconds by default. That would prevent surprises for any folks who may have missed that section of the functions/Lambda documentation.

**Comment by sw-yx** [comment]
PR welcome!

**Comment by 8eecf0d2** [comment]
@sw-yx should stalebot really be adding `wontfix` label?

**Comment by sw-yx** [comment]
probably not haha i just set it up w default settings

**Comment by davesag** [comment]
You can request longer timeouts from Netlify up to a max of 15 minutes so I think making it a setting rather than a fixed timeout would be preferable.

**Comment by sw-yx** [comment]
thanks dave. PR still welcome but this isnt a high pri for me rn

**Comment by sw-yx** [comment]
resovled in v 1.4.0 https://github.com/netlify/netlify-lambda/releases/tag/1.4.0 thanks to naipath!

**Comment by michaek** [comment]
Thanks!
