### ISSUE TITLE
Third party libraries not working in function

### ISSUE THREAD

**Issue by elliottross23** [netlify/netlify-lambda#46]
I'm trying to use `node-fetch` in my function but keep getting the Cannot find module 'node-fetch' error. This error only happens on a deployed function but works locally.

func.js
```
const fetch = require('node-fetch');

exports.handler = async (event, context) => {
	const result = await fetch('www.google.com', {
		method: 'GET',
	}).catch((err) => {
		// boo hoo
	});

	return {
		statusCode: 200,
		body: 'Badabing badaboom.'
	};
};
```

My folder structure is
```
netlify-functions/
    func.js
package.json
```

any ideas?

**Comment by imorente** [comment]
do you have the node-fetch dependency declared in your package.json?

There's an example that uses node-fetch in https://github.com/netlify/netlify-functions-example

**Comment by elliottross23** [comment]
Thanks for the great example. the issue was that i had specified in the netlify.toml file the directory where my functions were located instead of where to output them...

The docs say  `# This is where we will look for your lambda functions` and I thought that meant during build (since its under the build step) so it might need to be more clear that this is where the functions will be deployed
