### ISSUE TITLE
process.env not completely passed to DefinePlugin

### ISSUE THREAD

**Issue by richtera** [netlify/netlify-lambda#47]
During the build process the system reads the envrionment variables from the toml config, but will not include environment variables defined inside of the Environment panel in netlify or any environment variables defined within the build process. I added a additionalConfig webpack and define a new DefinePlugin.

**Comment by whmountains** [comment]
I have the the same problem.

Do you mind sharing what you put in the additional configuration.  My configuration is getting errors:

```js
const webpack = require('webpack')

module.exports = {
  plugins: [new webpack.DefinePlugin({ STRIPE_API_KEY: 'just_testing' })],
}
```

The error is, "TypeError: Cannot read property 'compilation' of undefined".

**Comment by richtera** [comment]
The key inside of the define object needs to be the full var name and needs to be valid json:
```
{ 'process.env.STRIPE_API_KEY': JSON.stringify("spikey") }
```

**Comment by sw-yx** [comment]
hi @whmountains  - we've upgraded to v4 now - hope that helps?

hi @richtera  - doubt we'll have access to the Environment panel in netlify. as for your webpack config solution.. i dont think thats the most secure?
