### ISSUE TITLE
Getting netlify-lambda working with React-Router

### ISSUE THREAD

**Issue by dbrrt** [netlify/netlify-lambda#53]
I'm getting difficulties while configuring a proxy working with React-Router to use a proxy cohabiting with my existing routes.

Is it possible to set up an equivalent to a Route with a path like `/.netlify/functions/${lambda-func}` to handle lambda calls, via the proxy (to http://localhost:9000 for instance) inside a React application with React-Router?

Thanks in advance.

**Comment by sw-yx** [comment]
i'm not sure i follow at all. netlify-lambda has nothing to do with React Router...

**Comment by dbrrt** [comment]
@sw-yx Good point, the problem will appear in any modern application with client-side routing, not only react-router.
