### ISSUE TITLE
queryStringParameters object structure differs from deployment environment

### ISSUE THREAD

**Issue by Neo-Oli** [netlify/netlify-lambda#54]
We have a request that looks something like this:
```
?filter[0][field]=title&filter[0][value]=TestElement&filter[1][field]=category&filter[1][value]=CategoryName
```
And in the development environment's lambda  function the `event.queryStringParameters`, will be a nested object/array construct like this:
```
{
    "filter": [
        {
            "field": "title",
            "value": "TestElement"
        },
        {
            "field": "category",
            "value": "CategoryName"
        }
    ]
}
```

But in our deployment environment it will be a flat object like this:
```
{
    "filter[0][field]" : "title",
    "filter[0][value]" : "TestElement",
    "filter[1][field]" : "category",
    "filter[1][value]" : "CategoryName"
}
```

It should be the same in both environments.

**Comment by sw-yx** [comment]
verified. cc @fool .

**Comment by fool** [comment]
does your fix close this issue @sw-yx ?  if so I'd close this ;)
