### ISSUE TITLE
npm start:lambda doesn't work -> answer: use npm run start:lambda

### ISSUE THREAD

**Issue by renschler** [netlify/netlify-lambda#56]
I was following the instructions here: https://www.netlify.com/docs/functions/#configuring-the-functions-folder

and installed netlify-lambda with:
`npm install netlify-lambda`

Then I created the appropriate netlify.toml file, but when I go to run with `netlify-lambda serve` I get the follow error:

Patrick$ `netlify-lambda serve src/lambda`
-bash: `netlify-lambda: command not found`

I checked and netlify-lambda is present the node_modules folder, so I'm not sure what I did wrong.

Thanks for the help.

NPM version: 5.6.0
node version: v8.11.4

Udpate: I also tried cloning the https://github.com/netlify/create-react-app-lambda repo, and then installed the dependencies with npm, and then tried to netlify-lambda serve, and I got the same error.

**Comment by madsobel** [comment]
When you install the package like that you make it available for npm but not globally.
So either:
1: Install it globally with the -g flag (not recommended) or..
2: Add an npm script like https://github.com/netlify/create-react-app-lambda/blob/master/package.json#L13 (recommended) then you can run `npm start:lambda`

**Comment by renschler** [comment]
thanks @madsobel 

but I should have mentioned I also tried `npm start:lambda`, that script comes with the create-react-app-lambda. Maybe I'm still doing something wrong but when I try npm start:lambda I get the incorrect usage dump:

> mypc:create-react-app-lambda Patrick$ npm start:lambda
> 
> Usage: npm <command>
> 
> where <command> is one of:
>     access, adduser, bin, bugs, c, cache, completion, config,
>     ddp, dedupe, deprecate, dist-tag, docs, doctor, edit,
>     explore, get, help, help-search, i, init, install,
>     install-test, it, link, list, ln, login, logout, ls,
>     outdated, owner, pack, ping, prefix, profile, prune,
>     publish, rb, rebuild, repo, restart, root, run, run-script,
>     s, se, search, set, shrinkwrap, star, stars, start, stop, t,
>     team, test, token, tst, un, uninstall, unpublish, unstar,
>     up, update, v, version, view, whoami
> 
> npm <command> -h     quick help on <command>
> npm -l           display full usage info
> npm help <term>  search for help on <term>
> npm help npm     involved overview
> 
> Specify configs in the ini-formatted file:
>     /Users/Patrick/.npmrc
> or on the command line via: npm <command> --key value
> Config info can be viewed via: npm help config
> 
> npm@5.6.0 /usr/local/lib/node_modules/npm

**Comment by renschler** [comment]
ahh I figured it out, I need to do `npm run start:lambda` not `npm start:lambda`

this post helped me: https://stackoverflow.com/questions/23547061/npm-package-json-scripts-not-being-called

**Comment by splex7** [comment]
npm run start:lambda ....OOPS....This is exactly what i want to know!!
