### ISSUE TITLE
Custom webpack config

### ISSUE THREAD

**Issue by kantle** [netlify/netlify-lambda#6]
Thanks for adding support for this in Version 0.2.0.

I believe this was only added for the build, not serve command. If you look at line 63 of build.js you see that additionalConfig is passed to webpackConfig, however in lines 73 and 74 additionalConfig is not passed. The result is that custom webpack configs are incorporated when running build -c, but not when running serve -c.

**Comment by verythorough** [comment]
Closed by #14
