### ISSUE TITLE
Handlers that serves jpg / static image not returning correct image 

### ISSUE THREAD

**Issue by isaurav0** [netlify/netlify-lambda#630]
I want lambda function to serve png/jpg image using golang.

**Steps To Reproduce**
Here's **go.mod** file.
```
module github.com/someone/downloader

go 1.18

require github.com/aws/aws-lambda-go v1.36.1

```

**main.go** looks like:
```
package main

import (
	"context"
	"encoding/base64"
	"io/ioutil"
	"net/http"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
)

func handler(ctx context.Context, request events.APIGatewayProxyRequest) (*events.APIGatewayProxyResponse, error) {

	url := "https://en.meming.world/images/en/a/a1/My_Time_Has_Come.jpg"

	// download image as save it as imageBytes
	response, err := http.Get(url)
	if err != nil {
		return nil, nil
	}
	defer response.Body.Close()

	imageBytes, err := ioutil.ReadAll(response.Body)
	if err != nil {
		return nil, nil
	}

	// convert to base64 string
	imageBase64 := base64.StdEncoding.EncodeToString(imageBytes)

	// send back response
	return &events.APIGatewayProxyResponse{
		StatusCode: http.StatusOK,
		Headers: map[string]string{
			"Content-Type":                 "image/png",
			"Access-Control-Allow-Origin":  "*",
			"Access-Control-Allow-Headers": "Content-Type",
		},
		Body:            imageBase64,
		IsBase64Encoded: true,
	}, nil
}

func main() {
	lambda.Start(handler)
}

```

I expect it to return this image.
<img width="853" alt="image" src="https://user-images.githubusercontent.com/46840490/211130356-2a8373f4-afaf-4836-b6cc-07915ce5586d.png">

But I'm getting a weird image with rectangular box instead. 
<img width="984" alt="image" src="https://user-images.githubusercontent.com/46840490/211131009-eddcd2a7-fad5-43cb-aa15-3d821d9951b7.png">

`netlify dev` is the command I'm using to run it locally.

I was told it relates to this [issue](https://github.com/netlify/netlify-lambda/issues/26) in a [stackoverflow post](https://stackoverflow.com/questions/75029343/why-is-aws-lambda-function-not-returning-jpg-png-images-when-executed-from-netli) that i made.

**Comment by danez** [comment]
Did you find a solution? This seems unrelated to this repository.

If you still have this issue, please report this in the [Netlify CLI repository](https://github.com/netlify/cli/issues/new/choose) or in our [support forums](https://answers.netlify.com/).

**Comment by osintalex** [comment]
This still exists for me, I gave up on doing this in netlify.
