### ISSUE TITLE
Function invocation failed: TypeError: n is not a function

### ISSUE THREAD

**Issue by TylerBarnes** [netlify/netlify-lambda#64]
Hi there,
I'm attempting to use a lambda function to use the node wpapi library
https://github.com/WP-API/node-wpapi

For some reason when I try to instantiate a new instance of their WPAPI class I get the error `Function invocation failed: TypeError: n is not a function`

I don't believe this is a problem with netlify-lambda but I'm wondering if someone could give me some guidance on debugging this. Is there something I need to add to my config to make it run? Or is there some way for me to figure out why n is not a function? The error comes from the minified code so it's hard to understand what's happening

**Comment by TylerBarnes** [comment]
Ok, I played around with this some more and actually if I run serve and then just copy paste my JS into the js file that's being served, it works fine. It seems like this might be a problem with the way netlify-lambda is minifying my script

**Comment by i8ramin** [comment]
I'm so getting the same error, but due to other reasons. For me it happens when I require the auth0-node Management Client code. 

Is there a way to turn off the js minification so we can debug these issues better?

**Comment by i8ramin** [comment]
FYI, I was able to disable the uglification of the functions locally by passing in my own webpack config like so:

Create a webpack overrides file (mine lives in `./config/webpack.functions.js`)

```
module.exports = {
  mode: "development"
}
```

Start the local server by passing in my local config

```
netlify-lambda -c ./config/webpack.functions.js serve src/functions
```

I can see the non-uglified version of the code now. For me, the error is:

```
Error during invocation:  TypeError: require is not a function
    at Object.../../node_modules/formidable/lib/incoming_form.js (/Users/ramin/Work/wework/labs/labs-ui/functions/pr-merge.js:41728:14)
```

And the corresponding line of code:

```
var crypto = require('crypto');
```

Looking through the rest of the generated file, it seems that some parts of the code are not being processed by babel, so there are regular `require` calls, whereas the rest of the code is using `__webpack_require__`.

Gotta look into the `auth0-node` files and its dependencies to see why this is happening.

**Comment by i8ramin** [comment]
A bit more context on my specific issue. Noticed that `require` is being re-defined right above the line where it errors out.

```
/***/ "../../node_modules/formidable/lib/incoming_form.js":
/*!******************************************************************************************!*\
  !*** /Users/ramin/Work/wework/labs/labs-ui/node_modules/formidable/lib/incoming_form.js ***!
  \******************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var require;if (global.GENTLY) require = GENTLY.hijack(__webpack_require__("../../node_modules/formidable/lib sync recursive"));

var crypto = require('crypto');
```

**Comment by TylerBarnes** [comment]
Awesome, I think this will help me troubleshoot as well! Thanks for sharing

**Comment by sw-yx** [comment]
hey both,

sorry for the delayed response and thanks for sharing. if theres anything that you can contribute upstream to babel too, that would probably be good as minification shouldnt ever cause bugs like this :( but i am glad you figured it out.

**Comment by DominicTobias** [comment]
Thanks this is happening with `faunadb` too and global.GENTLY fixed it. Would like to find out more about why it is though since so many major modules should not be breaking it must be something wrong in the netlify webpack config?

**Comment by sw-yx** [comment]
@DominicTobias we are releasing something this week which may help with this. looking forward to see if it solves your issue.

**Comment by connor11528** [comment]
I'm getting the same error as above. When I fire up my lambda functions to listen locally I get a warning:

```
WARNING in ../node_modules/formidable/lib/incoming_form.js 1:43-50
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

Then when I triggered my function get the same error as OP

```
Error during invocation:  TypeError: n is not a function
```

I tried adding the webpack plugin like @i8ramin mentioned. I'm using Gatsby so added to *gatsby-node.js* file like so:

```
 const webpack = require('webpack');

exports.onCreateWebpackConfig = ({
  stage,
  rules,
  loaders,
  plugins,
  actions,
}) => {
  actions.setWebpackConfig({
    plugins: [
     new webpack.DefinePlugin({ "global.GENTLY": false })
    ],
  })
}
```
But it did not help. Still getting both of the above errors. Is there a better way to add the above webpack config into Gatsby?

**Comment by TylerBarnes** [comment]
@connor11528 check out Netlify Dev!

https://www.youtube.com/watch?v=RL_gtVZ_79Q

As far as I can tell it either makes this repo obsolete or much less necessary.

**Comment by connor11528** [comment]
@TylerBarnes oh gnar will have to look into it. Thanks!

**Comment by castilh0s** [comment]
@connor11528 do you solved that? I'm with the same problem here and I'm can't figure out how to solve this...

**Comment by sw-yx** [comment]
@castilh0s give Netlify Dev a try. thats the solution i suggested further up. gonna lock this for now, pls open new issue with repro details if you need to pursue further
