### ISSUE TITLE
Add `shebang-loader` by default?

### ISSUE THREAD

**Issue by moltar** [netlify/netlify-lambda#65]
There are some node modules that begin with a shebang and current setup fails to consume those properly failing with:

```
[functions] Error during invocation:  Error: Module parse failed: Unexpected character '#' (1:0)
[functions] You may need an appropriate loader to handle this file type.
[functions] | #!/usr/bin/bin/env node
```

The `shebang-loader` loader fixes the issue.

I fixed it by adding a custom config override, but it'd be probably beneficial for others too.

If you want me to submit a PR, let me know I can do that.

**Comment by sw-yx** [comment]
pr still welcome

**Comment by sw-yx** [comment]
closing: netlify-lambda will only accept bugfixes for now.
