### ISSUE TITLE
Debug lambda functions locally

### ISSUE THREAD

**Issue by Safi1012** [netlify/netlify-lambda#71]
Hi,

is there a way to debug lambda functions locally? I already looked in the docs, but did't find anything which points in that direction.

I'm missing the ability to set an ```--inspect``` flag (which is common when debugging node applications) or something similar to start a debug mode, when serving my lamdba functions with ```netlify-lambda serve```.

I know that I can log everything with ```console.log()```, but this can be a bit tedious. 

Am I missing something here? 
Any help would be greatly appreciated!

**Comment by stefan--** [comment]
see https://github.com/netlify/netlify-lambda/pull/83
