### ISSUE TITLE
Typescript local import

### ISSUE THREAD

**Issue by MatthewAlner** [netlify/netlify-lambda#79]
I made a quick test project to try out the new Typescript support structure looks like this.

```
.
├── functions
│   ├── jokeTypescript.js
│   └── jokeVanilla.js
├── netlify.toml
├── package.json
├── src_functions
│   ├── jokeTypescript.ts
│   ├── jokeVanilla.js
│   └── utils
│       └── direction.ts
└── yarn.lock
```

when I try to import something local like this

```
import { Direction } from './utils/direction';
```

in jokeTypescript.ts, I get an error in the build like this

```
ERROR in ./jokeTypescript.ts
Module not found: Error: Can't resolve './utils/direction' in '/Users/matt/sandbox/nl-test/src_functions'
 @ ./jokeTypescript.ts 6:0-46 19:21-30
```

external imports like `import * as request from 'request-promise-native';` seem to work though

any thoughts?

**Comment by 8eecf0d2** [comment]
Pulling straws here, but could be an issue with default typescript options (can't see a `tsconfig.json` in your example).

Maybe try adding `include` to the `tsconfig.json`?
```json
{
  ...
  "include": [ "src_functions/**/*.ts" ],
}
```

**Comment by MatthewAlner** [comment]
I was hopeful but unfortunately that didn't do the trick. I'll push a demo somewhere to help with the debugging but more than likely i'm just missing something obvious.

**Comment by MatthewAlner** [comment]
OK so I made a blank ng6 project as that where i'm having the issue in real life

https://github.com/MatthewAlner/netlify-lambda-typescript-test

`yarn nlb` => build lambdas
`yarn nls` => serve lambdas
`yarn start` => run up angular

any thoughts would be helpful thanks

**Comment by sw-yx** [comment]
thanks for filing this - we do need a test fixture for the typescript stuff. i am not gonna get to this this week - pinging @mottox2 who added the typescript support to see if they can help

**Comment by mottox2** [comment]
Lastest release (`v.1.0.3`) don't support TypeScript. 
Perhaps it may be solved by releasing it, but I think webpack setting may be insufficient.

**Comment by MatthewAlner** [comment]
It's using master `"netlify-lambda": "https://github.com/netlify/netlify-lambda"`

https://github.com/MatthewAlner/netlify-lambda-typescript-test/blob/fffb878a03544c17f8bb0c09402e8c7c48311b47/package.json#L27

**Comment by MatthewAlner** [comment]
Awesome thanks @mottox2 that does the trick!

just a thought could we add something like.
```
    if (fs.readdirSync(path.join(process.cwd(), dir)).some(file => file.match(/\.(ts)$/))) {
      babelOpts.presets.push("@babel/preset-typescript");
    }
```

in the `webpackConfig` function in `build` so we wouldn't need the separate `.babelrc`? you could just change the file extension from `js` to `ts` and it would just work

**Comment by mottox2** [comment]
@MatthewAlner @sw-yx 
I agree with that opinion that we wouldn't need the separate `.babelrc`. I would like to add `@babel/preset-typescript` to default babel preset. 

How is that?

**Comment by Levino** [comment]
Is there any fix for the originally reported bug?

**Comment by Levino** [comment]
I see. Until the PR has been merged one can add the [correct `extensions` array](https://github.com/netlify/netlify-lambda/blob/ef6a5d76fd1ead5e2382f8c59eb2057579fcfc74/lib/build.js#L51) to ones own webpack.config.js

**Comment by sw-yx** [comment]
hi, sorry i was MIA for a bit. I will merge this now

**Comment by tomasfrancisco** [comment]
Am I the only one still having issues with local imports?
Not sure what I'm missing.

**Comment by sw-yx** [comment]
can you open a new issue and report what versions youre using please? this one is a bit old
