### ISSUE TITLE
Running `serve` command wipes out function code

### ISSUE THREAD

**Issue by alexmacarthur** [netlify/netlify-lambda#8]
Hopefully I'm not missing a configuration option or something... 

When I run the `serve` command, the code in my /functions/whatever.js appears to be processed by Webpack, wiping out the precompiled code I had written. As a makeshift solution, I've wrapped been first copying the precompiled file to a different directory to preserve it, but would not like to keep that up long term.

**Comment by bcomnes** [comment]
Do you have an example repo or gist to clarify the issue?  Not quite catching the full issue here.

**Comment by alexmacarthur** [comment]
Actually, it looks like I just didn't read the documentation fully. It says here to, at build time, put them into the functions directory because everything in there is what gets run through Webpack. 

https://functions-alpha--www.netlify.com/docs/lambda-functions/#configuring-the-functions-folder

I was having the same issue described here: 
https://gitter.im/netlify/lambda-functions?at=5a5ccae15a9ebe4f758cb1d7

Closing because of this misunderstanding -- thx!

**Comment by bcomnes** [comment]
Cool, glad it worked out.  And you are on gitter! 🙌
