### ISSUE TITLE
Use git tags and releases

### ISSUE THREAD

**Issue by Levino** [netlify/netlify-lambda#82]
Which commit is currently published on npm?

**Comment by sw-yx** [comment]
Hi @Levino - i've been merging a couple things but havent had bandwidth to double check before publish - will get to this soon and add a release tag

**Comment by sw-yx** [comment]
@Levino v1.1 is up :)

**Comment by Levino** [comment]
Cool. Just push the tags when you create new releases with `npm publish` or `yarn publish`.

**Comment by sw-yx** [comment]
huh, TIL. i'd been using `git tag`.
