### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by stewartduffy** [netlify/netlify-lambda#88]
First of this is awesome. Only one thing that seems to have me stumped is logging. I have a number of console.log statements in my functions, however when they are executed in production in the functions console in the netlify dashboard I only see something like this

```
7:42:55 AM: locations invoked
7:51:43 AM: locations invoked
``` 
I have also tried a number of other loggers https://github.com/winstonjs/winston & https://github.com/pinojs/pino but with no luck.

Is there some sort of environment variable I need to set or some other trick to get logging working in production?

Thanks in advance.

**Comment by futuregerald** [comment]
@stewartduffy Are you having trouble logging functions that you are running locally or those that are deployed on netlify? If you are having trouble with functions deployed to netlify then you should write in to netlify support at support@netlify.com.
