### ISSUE TITLE
No response when an argument isn't passed (or an invalid argument)

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/netlify-lambda#95]
When I first tried the CLI, I forgot the `serve` part. So I typed: `netlify-lambda functions`. The CLI didn't report anything. I then tried `netlify-lambda` by itself just to ensure it was working, and again, it had no output.

**Comment by sw-yx** [comment]
gonna just tag this as a good first issue for contribution :)

**Comment by sw-yx** [comment]
bump

**Comment by JakePartusch** [comment]
I think this should be closed from PR #102?

**Comment by sw-yx** [comment]
so it is!
