### ISSUE TITLE
Doc issue and capitalization

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/netlify-lambda#96]
I noticed in the Netlify docs (https://www.netlify.com/docs/functions/) it says to use `functions  = "..."` in your toml file. In the readme file here, it says to use `Functions`. Does case matter? Even if not, I'd make them match.

**Comment by sw-yx** [comment]
case doesnt matter, but i've been told capitalization is preferred. in this case i think our docs should be fixed. thanks for heads up. cc @verythorough

**Comment by verythorough** [comment]
Actually, we're standardizing in the other direction! #101 fixes this.

**Comment by sw-yx** [comment]
oops. my bad
