### ISSUE TITLE
Error about source and publish folder

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/netlify-lambda#97]
I'm following the docs and when I run `netlify-lambda serve functions` I get:

```
netlify-lambda: Starting server
/usr/lib/node_modules/netlify-lambda/lib/build.js:37
    throw new Error(
    ^

Error: Function source and publish folder should be in different locations
```

No idea what to do with this. I'm assuming my netlify.toml file needs something, but I didn't have one before. I only added one per docs to specify my functions folder.

**Comment by cfjedimaster** [comment]
I'm not using a build/serve folder. Per the docs, I had made a folder (functions), and put my test file there. I'm using Git for my Netlify project and it deploys fine when I commit. I want to test locally to make it a bit quicker though. The docs just say to use `netlify-lambda  server folder` which I assume should be functions, right? This may be a doc bug and not a CLI bug of course.

**Comment by sw-yx** [comment]
yes im telling you that i think your issue is that your netlify.toml specifies the `functions` folder. 

netlify-lambda uses that as a build folder. so you’re trying to build from your source folder `functions` (specified in your command `netlify-lambda serve functions`) to your build/serve folder `functions` (specified in `netlify.toml`), and that would of course overwrite your source, which is why we put that error there.

can you try renaming your functions folder in netlify.toml to anything else and see if that works?

**Comment by cfjedimaster** [comment]
But doesn't the docs say this setting is supposed to be where Netlify can find your functions? 

So I changed it to function2.

In the CLI, I did: `netlify-lambda serve function`. 

The server starts up, but I get this:

    ERROR in Entry module not found: Error: Can't resolve 'babel-loader' in '/mnt/c/projects/codabreaker/functions'

Ignoring that, I tried to hit http://localhost:9000/functions/test and it gave me this error: `Function invocation failed: Error: Cannot find module '/mnt/c/projects/codabreaker/functions2/functions'`. Which I guess makes sense, I don't have that folder. My JavaScript file lives in the functions folder.

**Comment by cfjedimaster** [comment]
An update. I'm following this tutorial (https://travishorn.com/netlify-lambda-functions-from-scratch-1186f61c659e) and I've made some discovering and progress, but still can't proceed. 

a) In this tutorial, the author has netlify-lambda installed in the project directly instead of globally. This *is* documented and I missed it.
b) I now get this error:

```
Unhandled rejection Error: Cannot find module '/mnt/c/projects/codabreaker/lambda/test'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:32:19)
```

Almost like it isn't doing the build first?

**Comment by cfjedimaster** [comment]
Ok, so this is weird. I ran a build one time. I then ran serve again and it worked. My first test had a bug in my function that I fixed, and apparently it rebuilt automatically. Yep, I've confirmed that.

So it looks like an initial build is required, but it isn't documented? As it only says you do the build to prepare for deployment.

**Comment by sw-yx** [comment]
hey Raymond, sorry for the slow response as i have been traveling. initial build is NOT required.

i will update the install instructions to make local install more explicit.

i'm sorry for all the trouble you are facing but at this point i'm not at all sure what issues you have. is this still about source vs publish folder? or has the issue morphed into something else?

i recorded this video today to show setting up netlify-lambda from scratch https://www.youtube.com/watch?v=3ldSM98nCHI i made a couple mistakes but really it isnt that complex as you can see from the video. hopefully you'll spot some difference and be able to resolve.

**Comment by cfjedimaster** [comment]
Not sure what to say but for me, the initial build was required. Also, if I added a new function, I had to run build again. After that, the serve command correctly saw updates to source files. I wrote up my experiences here: https://www.raymondcamden.com/2019/01/08/adding-serverless-functions-to-your-netlify-static-site

**Comment by sw-yx** [comment]
yea the watch doesnt detect new files being added.

your blogpost is really great! I'm gonna add it to the README for others. and please of course feel free to PR/file an issue for any improvements you'd like to the README. docs can always be better.

**Comment by sw-yx** [comment]
closing - it seems feedback has been received. will have updates to hopefully improve the dx for cfjedi and others soon.

**Comment by elie222** [comment]
Yup. This has been quite confusing.

**Comment by aamorozov** [comment]
It wasn't clear from the docs indeed but the comments on this thread helped me resolve the same issue. 
For those who lands here, your `functions` field in the build step in `netlify.toml` should have a `./functions` path, while the src of the actual function should be named differently, i.e. `lambda_functions`, etc.

For example,
#### netlify.toml:

```
[build]
  command = "yarn build"
  publish = "./path"
  functions = "./functions"
```

#### your script in package.json:
```
build: netlify-lambda build PATH_TO_DIR_WITH_FUNCTIONS_THAT_NAMED_NOT_FUNCTIONS`
```

**Comment by sw-yx** [comment]
indeed. PR welcome for clearer docs.
